const bearTitle = '熊宝';
const bearItems = [
  {
    id: 'bear_back_all_china',
    ver: ['limit', 'rr', 'p', 'h'],
    image: './images/item/china/bear_back_all_china.jpeg',
    buyLink: 'https://weidian.com/item.html?itemID=6698120841',
    title: '【菲首】一键毕业',
    brand: ['JYP', 'MK'],
    hit: ['1限+2普+1P+1H'],
    descLink: '',
    price: '¥ 382',
    shipping: 'back',
    onlyFelix: false,
    allVersion: true,
    ribbon: '',
    fansite: 'china',
  },
  {
    id: 'bear_back_el_china',
    ver: ['rr'],
    image: './images/item/china/bear_back_el_china.jpeg',
    buyLink: 'https://weidian.com/item.html?itemID=6731315797',
    title: '【菲首】普版',
    brand: ['EL'],
    hit: ['可指定成员'],
    descLink: '',
    price: '¥ 78',
    shipping: 'back',
    onlyFelix: true,
    allVersion: false,
    ribbon: '',
    fansite: 'china',
  },
  {
    id: 'bear_back_china',
    ver: ['rr', 'p', 'h'],
    image: './images/item/china/bear_back_china.jpeg',
    buyLink: 'https://weidian.com/item.html?itemID=6680733841',
    title: '【菲首】普版 / P版 / H版',
    brand: ['JYP', 'MK', 'MP', 'BDM', 'SW', 'WM', 'MMT', 'MS'],
    hit: [],
    descLink: '',
    price: '¥ 50~85',
    shipping: 'back',
    onlyFelix: false,
    allVersion: false,
    ribbon: '',
    fansite: 'china',
  },
  // gem
  {
    id: 'bear_back_gem',
    ver: ['rr', 'p', 'h'],
    image: './images/item/gem/bear_back_gem.jpeg',
    buyLink: 'https://weidian.com/item.html?itemID=6681806286',
    title: '【宝石】普版 / P版 / H版',
    brand: ['JYP', 'MK', 'MP', 'BDM', 'SW', 'WM', 'MMT'],
    hit: [],
    descLink: '',
    price: '¥ 50~85',
    shipping: 'back',
    onlyFelix: false,
    allVersion: false,
    ribbon: '',
    fansite: 'gem',
  },
]