const bearTitle = '熊宝';
const bearItems = [
  {
    id: 'bear-back-abc-china',
    ver: ['abc'],
    image: './images/bear-back-abc.jpg',
    buyLink: 'https://shop881578129.v.weidian.com/item.html?itemID=6264265561',
    title: '普版',
    brand: ['SW', 'YES24', 'MP', 'JYP', 'BDM', 'MS', 'WM', 'MMT', 'EL'],
    hit: [],
    descLink: '',
    price: '¥ 74~93',
    shipping: 'back',
    onlyFelix: false,
  },
  {
    id: 'bear-back-d-china',
    ver: ['d'],
    image: './images/bear-back-abc.jpg',
    buyLink: 'https://shop881578129.v.weidian.com/item.html?itemID=6264265561',
    title: 'D版',
    brand: ['SW', 'YES24', 'MP', 'JYP', 'BDM'],
    hit: [],
    descLink: '',
    price: '¥ 50~61',
    shipping: 'back',
    onlyFelix: false,
  },
  {
    id: 'bear-back-abc-gem',
    ver: ['abc'],
    image: './images/bear-back-abc-gem.jpg',
    buyLink: 'https://shop881578129.v.weidian.com/item.html?itemID=6264445641&spider_token=e13b',
    title: '普版',
    brand: ['SW', 'YES24', 'MP', 'JYP', 'BDM', 'MS', 'WM', 'MMT', 'EL'],
    hit: [],
    descLink: '',
    price: '¥ 74~93',
    shipping: 'back',
    onlyFelix: false,
  },
  {
    id: 'bear-back-d-gem',
    ver: ['d'],
    image: './images/bear-back-abc-gem.jpg',
    buyLink: 'https://shop881578129.v.weidian.com/item.html?itemID=6264445641&spider_token=e13b',
    title: 'D版',
    brand: ['SW', 'YES24', 'MP', 'JYP', 'BDM'],
    hit: [],
    descLink: '',
    price: '¥ 50~61',
    shipping: 'back',
    onlyFelix: false,
  },
  {
    id: 'bear-back-abc-bdn-china',
    ver: ['abc'],
    image: './images/bear-back-abc_bandina.jpg',
    buyLink: 'https://shop881578129.v.weidian.com/item.html?itemID=6277798098',
    title: '普版',
    brand: ['BDN'],
    hit: [],
    descLink: '',
    price: '¥ 87',
    shipping: 'back',
    onlyFelix: false,
  },
]