const goodsTitle = '自制特典';
const goodsItems = [
  {
    id: 'earring',
    image: './images/goods/earring.jpeg',
    buyLink: 'https://weidian.com/item.html?itemID=6641725591',
    title: '【菲首】呢喃耳语·耳饰',
    brand: [],
    hit: [],
    descLink: 'https://weibo.com/6375947740/NkvlnAavS',
    price: '¥ 38',
  },
  {
    id: 'slippers',
    image: './images/goods/slippers.jpeg',
    buyLink: 'https://weidian.com/item.html?itemID=6667668964',
    title: '【菲首】爱的圆舞曲·毛绒拖鞋',
    brand: [],
    hit: [],
    descLink: 'https://weibo.com/6375947740/NlGb2nYrZ',
    price: '¥ 28',
  },
  {
    id: 'printer',
    image: './images/goods/printer.jpeg',
    buyLink: 'https://weidian.com/item.html?itemID=6674992841',
    title: '【菲首】热敏打印机',
    brand: [],
    hit: [],
    descLink: 'https://weibo.com/6375947740/Nmh1L42in',
    price: '¥ 58',
  },
  {
    id: 'bag',
    image: './images/goods/bag.jpeg',
    buyLink: 'https://weidian.com/item.html?itemID=6692902224',
    title: '【菲首】自制特典腋下包',
    brand: [],
    hit: [],
    descLink: 'https://weibo.com/6375947740/Nn5LvB5WU',
    price: '¥ 66',
  },
  {
    id: 'pillow',
    image: './images/goods/pillow.jpeg',
    buyLink: 'https://weidian.com/item.html?itemID=6695131419',
    title: '【菲首】慵懒午后·小鸡抱枕',
    brand: [],
    hit: [],
    descLink: 'https://weibo.com/6375947740/Nnd6xCQzJ',
    price: '¥ 39.9',
  },
  {
    id: 'card-book',
    image: './images/goods/card-book.jpeg',
    buyLink: 'https://weidian.com/item.html?itemID=6662838382',
    title: '【宝石】毛绒卡册',
    brand: [],
    hit: [],
    descLink: 'https://weibo.com/5947554719/NloTjEmaX',
    price: '¥ 49.9',
  },
  {
    id: 'clothes',
    image: './images/goods/clothes.jpeg',
    buyLink: 'https://weidian.com/item.html?itemID=6678360161',
    title: '【宝石】芝士啵叽娃衣',
    brand: [],
    hit: [],
    descLink: 'https://weibo.com/5947554719/NmsSIjjT2',
    price: '¥ 52',
  },
]