const goodsTitle = '自制特典';
const goodsItems = [
  {
    id: '',
    ver: [''],
    image: './images/goods/goods-keyboard.jpg',
    buyLink: 'https://weidian.com/item.html?itemID=6324934044&wfr=c',
    title: '蓝牙键盘+K4 D版拆卡',
    brand: [],
    hit: ['可指定成员'],
    descLink: 'https://weibo.com/6375947740/N1w0I0x0C',
    price: '¥ 70',
    shipping: '',
    onlyFelix: false,
  },
  {
    id: '',
    ver: [''],
    image: './images/goods/goods-blocks.jpg',
    buyLink: 'https://cn.ktown4u.com/fanc_iteminfo?mst_fanc_goods_no=207806',
    title: '福福积木',
    brand: [],
    hit: [],
    descLink: '',
    price: '¥ 110+',
    shipping: '',
    onlyFelix: false,
  },
  {
    id: '',
    ver: [''],
    image: './images/goods/goods-blocks.jpg',
    buyLink: 'https://weidian.com/item.html?itemID=6271856382&wfr=c',
    title: '福福积木换购',
    brand: [],
    hit: [],
    descLink: 'https://weibo.com/6375947740/MEzwqz6FD',
    price: '¥ 66',
    shipping: '',
    onlyFelix: false,
  },
  {
    id: '',
    ver: [''],
    image: './images/goods/goods-fucat.jpg',
    buyLink: 'https://cn.ktown4u.com/fanc_iteminfo?mst_fanc_goods_no=207726',
    title: '馥喵团子+头套',
    brand: [],
    hit: [],
    descLink: '',
    price: '¥ 110+',
    shipping: '',
    onlyFelix: false,
  },
  {
    id: '',
    ver: [''],
    image: './images/goods/goods-necklace.jpg',
    buyLink: 'https://cn.ktown4u.com/fanc_iteminfo?mst_fanc_goods_no=207723',
    title: '项链',
    brand: [],
    hit: [],
    descLink: '',
    price: '¥ 87+',
    shipping: '',
    onlyFelix: false,
  },
  {
    id: '',
    ver: [''],
    image: './images/goods/goods-clothing.jpg',
    buyLink: 'https://cn.ktown4u.com/fanc_iteminfo?mst_fanc_goods_no=207678',
    title: '衣服',
    brand: [],
    hit: [],
    descLink: '',
    price: '¥ 90+',
    shipping: '',
    onlyFelix: false,
  },
  {
    id: '',
    ver: [''],
    image: './images/goods/goods-blush.jpg',
    buyLink: 'https://cn.ktown4u.com/fanc_iteminfo?mst_fanc_goods_no=207642',
    title: '橘朵腮红',
    brand: [],
    hit: [],
    descLink: '',
    price: '¥ 68+',
    shipping: '',
    onlyFelix: false,
  },
  {
    id: '',
    ver: [''],
    image: './images/goods/goods-cd.jpg',
    buyLink: 'https://cn.ktown4u.com/fanc_iteminfo?mst_fanc_goods_no=207639',
    title: 'CD机',
    brand: [],
    hit: [],
    descLink: '',
    price: '¥ 199+',
    shipping: '',
    onlyFelix: false,
  },
  {
    id: '',
    ver: [''],
    image: './images/goods/goods-scale.jpg',
    buyLink: 'https://cn.ktown4u.com/fanc_iteminfo?mst_fanc_goods_no=207636',
    title: '体重秤',
    brand: [],
    hit: [],
    descLink: '',
    price: '¥ 72+',
    shipping: '',
    onlyFelix: false,
  },
  {
    id: '',
    ver: [''],
    image: './images/goods/goods-cardBook.jpg',
    buyLink: 'https://cn.ktown4u.com/fanc_iteminfo?mst_fanc_goods_no=207633',
    title: '卡册',
    brand: [],
    hit: [],
    descLink: '',
    price: '¥ 93+',
    shipping: '',
    onlyFelix: false,
  },
  {
    id: '',
    ver: [''],
    image: './images/goods/goods-garageKit.jpg',
    buyLink: 'https://cn.ktown4u.com/fanc_iteminfo?mst_fanc_goods_no=207626',
    title: '手办',
    brand: [],
    hit: [],
    descLink: '',
    price: '¥ 105+',
    shipping: '',
    onlyFelix: false,
  },
  {
    id: '',
    ver: [''],
    image: './images/goods/goods-album.jpg',
    buyLink: '',
    modalID: 'goodsAlbum',
    title: '补砖',
    brand: [],
    hit: ['4/28前购买过自制特典'],
    descLink: 'https://weibo.com/6375947740/MEx5bsHxB',
    price: '',
    shipping: '',
    onlyFelix: false,
  },
  {
    id: '',
    ver: [''],
    image: './images/goods/gem-goods-1.jpg',
    buyLink: 'https://weidian.com/item.html?itemID=6185580672&wfr=c&ifr=itemdetail&source=goods_home&sfr=app&continueFlag=324dd2c5b3c9dacb74e9c06e79ebc5b2',
    title: '10cm鸡猫挂件',
    brand: [],
    hit: [],
    descLink: '',
    price: '¥ 16',
    shipping: '',
    onlyFelix: false,
  },
  {
    id: '',
    ver: [''],
    image: './images/goods/gem-goods-1.jpg',
    buyLink: 'https://weidian.com/item.html?itemID=6185580672&wfr=c&ifr=itemdetail&source=goods_home&sfr=app&continueFlag=324dd2c5b3c9dacb74e9c06e79ebc5b2',
    title: '60cm鸡猫玩偶',
    brand: [],
    hit: [],
    descLink: '',
    price: '¥ 40',
    shipping: '',
    onlyFelix: false,
  },
  {
    id: '',
    ver: [''],
    image: './images/goods/gem-goods-3.jpg',
    buyLink: 'https://weidian.com/item.html?itemID=6171957742&wfr=c&source=goods_home&ifr=itemdetail&sfr=app',
    title: '豆乳咪串珠',
    brand: [],
    hit: [],
    descLink: '',
    price: '¥ 22.6+',
    shipping: '',
    onlyFelix: false,
  },
  {
    id: '',
    ver: [''],
    image: './images/goods/gem-goods-4.jpg',
    buyLink: 'https://weidian.com/item.html?itemID=6152561948&wfr=c&ifr=itemdetail&source=goods_home&sfr=app&continueFlag=324dd2c5b3c9dacb74e9c06e79ebc5b2',
    title: '毛绒包',
    brand: [],
    hit: [],
    descLink: '',
    price: '¥ 66',
    shipping: '',
    onlyFelix: false,
  },
  {
    id: '',
    ver: [''],
    image: './images/goods/gem-goods-5.jpg',
    buyLink: 'https://weidian.com/item.html?itemID=6133294037&wfr=c&ifr=itemdetail&source=goods_home&sfr=app&continueFlag=324dd2c5b3c9dacb74e9c06e79ebc5b2',
    title: '穿戴甲',
    brand: [],
    hit: [],
    descLink: '',
    price: '¥ 36+',
    shipping: '',
    onlyFelix: false,
  },
  {
    id: '',
    ver: [''],
    image: './images/goods/gem-goods-6.jpg',
    buyLink: 'https://weidian.com/item.html?itemID=6100717617&wfr=c&ifr=itemdetail&source=goods_home&sfr=app&continueFlag=324dd2c5b3c9dacb74e9c06e79ebc5b2',
    title: '睡衣',
    brand: [],
    hit: [],
    descLink: '',
    price: '¥ 58',
    shipping: '',
    onlyFelix: false,
  },
  {
    id: '',
    ver: [''],
    image: './images/goods/gem-goods-7.jpg',
    buyLink: 'https://weidian.com/item.html?itemID=6205946835&wfr=c&ifr=itemdetail&source=goods_home&sfr=app&continueFlag=324dd2c5b3c9dacb74e9c06e79ebc5b2',
    title: '打包set',
    brand: [],
    hit: [],
    descLink: '',
    price: '¥ 19.15+',
    shipping: '',
    onlyFelix: false,
  },
  {
    id: '',
    ver: [''],
    image: './images/goods/goods-album-gem.jpg',
    buyLink: 'https://weibo.com/5947554719/MEcCIbQjZ',
    title: '补砖',
    brand: [],
    hit: [],
    descLink: 'https://weibo.com/5947554719/MEcCIbQjZ',
    price: '',
    shipping: '',
    onlyFelix: false,
  },
  {
    id: '',
    ver: [''],
    image: './images/goods/goods-fortune.jpg',
    buyLink: 'https://weidian.com/item.html?itemID=6340440610&wfr=c',
    title: 'Wheel of Fortune·命运之轮',
    brand: [],
    hit: [],
    descLink: 'https://weibo.com/6375947740/N2l23cgUm',
    price: '¥ 22.6',
    shipping: '',
    onlyFelix: false,
  },
  {
    id: '',
    ver: [''],
    image: './images/goods/goods-miracle.jpg',
    buyLink: 'https://weidian.com/item.html?itemID=6322273566&wfr=c',
    title: '卢馥宫·Miracle',
    brand: [],
    hit: [],
    descLink: 'https://weibo.com/6375947740/N1qt7kgST',
    price: '¥ 29.9',
    shipping: '',
    onlyFelix: false,
  },
  {
    id: '',
    ver: [''],
    image: './images/goods/goods-fruit.jpg',
    buyLink: 'https://weidian.com/item.html?itemID=6303558854&wfr=c',
    title: '馥郁果香',
    brand: [],
    hit: [],
    descLink: 'https://weibo.com/6375947740/N0o3MrrUk',
    price: '¥ 26.6',
    shipping: '',
    onlyFelix: false,
  },
  {
    id: '',
    ver: [''],
    image: './images/goods/goods-cardCover.jpg',
    buyLink: 'https://weidian.com/item.html?itemID=6268957377&wfr=c',
    title: '开车特典',
    brand: [],
    hit: [],
    descLink: 'https://weibo.com/6375947740/MEpgpufAj',
    price: '¥ 18.8+',
    shipping: '',
    onlyFelix: false,
  },
  {
    id: '',
    ver: [''],
    image: './images/goods/goods-ladder.jpg',
    buyLink: 'https://weidian.com/item.html?itemID=6266521802&wfr=c',
    title: '阶梯特典',
    brand: [],
    hit: [],
    descLink: 'https://weibo.com/6375947740/MEcEThuGL',
    price: '¥ 25+',
    shipping: '',
    onlyFelix: false,
  },
  {
    id: '',
    ver: [''],
    image: './images/goods/goods-deposit.jpg',
    buyLink: '',
    modalID: 'goodsDeposit',
    title: '啶金补款',
    brand: [],
    hit: [],
    descLink: 'https://weibo.com/6375947740/ME9mUdVWX',
    price: '',
    shipping: '',
    onlyFelix: false,
  },
]