const k4Title = 'K4';
const k4Items = [
  {
    id: 'k4-back-limited-k4-china',
    ver: ['limit'],
    image: './images/k4-limited.jpg',
    buyLink: 'https://cn.ktown4u.com/iteminfo?grp_no=1741898&fanc_goods_no=207496&goods_no=94038',
    title: '限量版',
    brand: ['K4'],
    hit: [],
    descLink: '',
    price: '¥ 66',
    shipping: 'back',
    onlyFelix: false,
  },
  {
    id: 'k4-back-abc-k4-china',
    ver: ['abc'],
    image: './images/k4-abc.jpg',
    buyLink: 'https://cn.ktown4u.com/iteminfo?grp_no=1741898&fanc_goods_no=207508&goods_no=94037',
    title: '普版',
    brand: ['K4'],
    hit: [],
    descLink: '',
    price: '¥ 65.5',
    shipping: 'back',
    onlyFelix: false,
  },
  {
    id: 'k4-back-abc-k4-3-china',
    ver: ['abc'],
    image: './images/k4-abc.jpg',
    buyLink: 'https://cn.ktown4u.com/iteminfo?grp_no=1741898&fanc_goods_no=207499&goods_no=94043',
    title: '普版 套装 (3本)',
    brand: ['K4'],
    hit: [],
    descLink: '',
    price: '¥ 196.5',
    shipping: 'back',
    onlyFelix: false,
  },
  {
    id: 'k4-back-d-k4-china',
    ver: ['d'],
    image: './images/k4-d.jpg',
    buyLink: 'https://cn.ktown4u.com/iteminfo?grp_no=1741898&fanc_goods_no=207507&goods_no=94035',
    title: 'D版',
    brand: ['K4'],
    hit: [],
    descLink: '',
    price: '¥ 45',
    shipping: 'back',
    onlyFelix: false,
  }
]