const k4Title = 'K4';
const k4Items = [
  {
    id: 'k4_back_limit_china',
    ver: ['limit'],
    image: './images/item/china/k4_back_limit_china.jpeg',
    buyLink: 'https://cn.ktown4u.com/iteminfo?grp_no=10649714&fanc_goods_no=269977&goods_no=101240',
    title: '',
    brand: [],
    hit: [],
    descLink: '',
    price: '¥ 93',
    shipping: 'back',
    onlyFelix: false,
    ribbon: '',
    fansite: 'china',
  },
  {
    id: 'k4_back_rr_china',
    ver: ['rr'],
    image: './images/item/china/k4_back_rr_china.jpeg',
    buyLink: 'https://cn.ktown4u.com/iteminfo?grp_no=10649714&fanc_goods_no=269972&goods_no=101243',
    title: '',
    brand: [],
    hit: [],
    descLink: '',
    price: '¥ 69',
    shipping: 'back',
    onlyFelix: false,
    ribbon: '',
    fansite: 'china',
  },
  {
    id: 'k4_back_rr_1_china',
    ver: ['rr'],
    image: './images/item/china/k4_back_rr_1_china.jpeg',
    buyLink: 'https://cn.ktown4u.com/iteminfo?grp_no=10649714&fanc_goods_no=269974&goods_no=101244',
    title: '',
    brand: [],
    hit: [],
    descLink: '',
    price: '¥ 138 (2CD SET)',
    shipping: 'back',
    onlyFelix: false,
    ribbon: '',
    fansite: 'china',
  },
  {
    id: 'k4_back_p_china',
    ver: ['p'],
    image: './images/item/china/k4_back_p_china.jpeg',
    buyLink: 'https://cn.ktown4u.com/iteminfo?grp_no=10649714&fanc_goods_no=269970&goods_no=101238',
    title: '',
    brand: [],
    hit: [],
    descLink: '',
    price: '¥ 52',
    shipping: 'back',
    onlyFelix: false,
    ribbon: '',
    fansite: 'china',
  },
  {
    id: 'k4_back_h_china',
    ver: ['h'],
    image: './images/item/china/k4_back_h_china.jpeg',
    buyLink: 'https://cn.ktown4u.com/iteminfo?grp_no=10649714&fanc_goods_no=269971&goods_no=101239',
    title: '',
    brand: [],
    hit: [],
    descLink: '',
    price: '¥ 52',
    shipping: 'back',
    onlyFelix: false,
    ribbon: '',
    fansite: 'china',
  },
]