const kpopmerchTitle = 'Kpopmerch';
const kpopmerchItems = [
  {
    id: 'kpopmerch_back_china',
    ver: ['rr', 'p', 'h'],
    image: './images/item/china/kpopmerch_back_china.jpeg',
    buyLink: 'https://weidian.com/item.html?itemID=6680688767',
    title: '【菲首】普通版 / P版 / H版',
    brand: [],
    hit: [],
    descLink: '',
    price: '¥ 45~65',
    shipping: 'back',
    onlyFelix: false,
    allVersion: false,
    ribbon: '',
    fansite: 'china',
  },
  {
    id: 'kpopmerch_back_gem',
    ver: ['rr', 'p', 'h'],
    image: './images/item/gem/kpopmerch_back_gem.jpeg',
    buyLink: 'https://weidian.com/item.html?itemID=6680761851',
    title: '【宝石】普通版 / P版 / H版',
    brand: [],
    hit: [],
    descLink: '',
    price: '¥ 45~65',
    shipping: 'back',
    onlyFelix: false,
    allVersion: false,
    ribbon: '',
    fansite: 'gem',
  },
]