const kramTitle = 'KR-AM音像店';
const kramItems = [
  {
    id: 'kram_back_all_china',
    ver: ['limit', 'rr', 'p', 'h'],
    image: './images/item/china/kram_back_all_china.jpeg',
    buyLink: 'https://weidian.com/item.html?itemID=6684045464',
    title: '',
    brand: [],
    hit: ['一键毕业', '1限+2普+1P+1H'],
    descLink: 'https://weibo.com/6375947740/NmJrAalJD',
    price: '¥ 306',
    shipping: 'back',
    onlyFelix: false,
    allVersion: true,
    ribbon: '',
    fansite: 'china',
  },
  {
    id: 'kram_back_limit_yes24_china',
    ver: ['limit'],
    image: './images/item/china/kram_back_limit_yes24_china.jpeg',
    buyLink: 'https://weidian.com/item.html?itemID=6680634197',
    title: '',
    brand: ['YES24'],
    hit: [],
    descLink: '',
    price: '¥ 90',
    shipping: 'back',
    onlyFelix: false,
    allVersion: false,
    ribbon: '',
    fansite: 'china',
  },
  {
    id: 'kram_back_rr_yes24_china',
    ver: ['rr'],
    image: './images/item/china/kram_back_rr_yes24_china.jpeg',
    buyLink: 'https://weidian.com/item.html?itemID=6683060472',
    title: '',
    brand: ['YES24'],
    hit: [],
    descLink: '',
    price: '¥ 164',
    shipping: 'back',
    onlyFelix: true,
    ribbon: '',
    fansite: 'china',
  },
  {
    id: 'kram_back_p_china',
    ver: ['p'],
    image: './images/item/china/kram_back_p_china.jpeg',
    buyLink: 'https://weidian.com/item.html?itemID=6681302379',
    title: '',
    brand: [],
    hit: [],
    descLink: '',
    price: '¥ 92',
    shipping: 'back',
    onlyFelix: true,
    ribbon: '',
    fansite: 'china',
  },
  {
    id: 'kram_back_rr_jyp_china',
    ver: ['rr'],
    image: './images/item/china/kram_back_rr_jyp_china.jpeg',
    buyLink: 'https://weidian.com/item.html?itemID=6681102547',
    title: '',
    brand: ['JYP'],
    hit: [],
    descLink: '',
    price: '¥ 91',
    shipping: 'back',
    onlyFelix: true,
    ribbon: '',
    fansite: 'china',
  },
  {
    id: 'kram_back_rr_mp_china',
    ver: ['rr'],
    image: './images/item/china/kram_back_rr_mp_china.jpeg',
    buyLink: 'https://weidian.com/item.html?itemID=6682105338',
    title: '',
    brand: ['MP'],
    hit: [],
    descLink: '',
    price: '¥ 78',
    shipping: 'back',
    onlyFelix: true,
    ribbon: '',
    fansite: 'china',
  },
  // gem
  {
    id: 'kram_back_all_gem',
    ver: ['limit', 'rr', 'p', 'h'],
    image: './images/item/gem/kram_back_all_gem.jpeg',
    buyLink: 'https://weidian.com/item.html?itemID=6684128732',
    title: '',
    brand: [],
    hit: ['一键毕业', '1限+2普+1P+1H'],
    descLink: 'https://weibo.com/5947554719/NmJAXzd0d',
    price: '¥ 306',
    shipping: 'back',
    onlyFelix: false,
    allVersion: true,
    ribbon: '',
    fansite: 'gem',
  },
  {
    id: 'kram_back_rr_yes24_gem',
    ver: ['rr'],
    image: './images/item/gem/kram_back_rr_yes24_gem.jpeg',
    buyLink: 'https://weidian.com/item.html?itemID=6683008660',
    title: '',
    brand: ['YES24'],
    hit: [],
    descLink: '',
    price: '¥ 164',
    shipping: 'back',
    onlyFelix: true,
    ribbon: '',
    fansite: 'gem',
  },
  {
    id: 'kram_back_p_gem',
    ver: ['p'],
    image: './images/item/gem/kram_back_p_gem.jpeg',
    buyLink: 'https://weidian.com/item.html?itemID=6682364262',
    title: '',
    brand: [],
    hit: [],
    descLink: '',
    price: '¥ 92',
    shipping: 'back',
    onlyFelix: true,
    ribbon: '',
    fansite: 'gem',
  },
  {
    id: 'kram_back_rr_jyp_gem',
    ver: ['rr'],
    image: './images/item/gem/kram_back_rr_jyp_gem.jpeg',
    buyLink: 'https://weidian.com/item.html?itemID=6681096837',
    title: '',
    brand: ['JYP'],
    hit: [],
    descLink: '',
    price: '¥ 91',
    shipping: 'back',
    onlyFelix: true,
    ribbon: '',
    fansite: 'gem',
  },
  {
    id: 'kram_back_rr_mp_gem',
    ver: ['rr'],
    image: './images/item/gem/kram_back_rr_mp_gem.jpeg',
    buyLink: 'https://weidian.com/item.html?itemID=6682223748',
    title: '',
    brand: ['MP'],
    hit: [],
    descLink: '',
    price: '¥ 78',
    shipping: 'back',
    onlyFelix: true,
    ribbon: '',
    fansite: 'gem',
  },
]