const mmtshopTitle = 'MMT SHOP';
const mmtshopItems = [
  {
    id: 'mmtshoop_back_rr_china',
    ver: ['rr'],
    image: './images/item/china/mmtshoop_back_rr_china.jpeg',
    buyLink: '',
    modalID: 'mmtQRcode',
    title: '【菲首】普版',
    brand: ['MMT'],
    hit: [],
    descLink: '',
    price: '¥ 78',
    shipping: 'back',
    onlyFelix: false,
    allVersion: false,
    ribbon: '',
    fansite: 'china',
  },
  {
    id: 'mmtshoop_back_rr_mmt_china',
    ver: ['rr'],
    image: './images/item/china/mmtshoop_back_rr_mmt_china.jpeg',
    buyLink: '',
    modalID: 'mmtFelixQRcode',
    title: '【菲首】MMT普版1+1',
    brand: ['MMT'],
    hit: [],
    descLink: '',
    price: '¥ 156',
    shipping: 'back',
    onlyFelix: true,
    allVersion: false,
    ribbon: '',
    fansite: 'china',
  },
]