const msTitle = 'MS';
const msItems = [
  {
    id: 'ms_back_rr_china',
    ver: ['rr'],
    image: './images/item/china/ms_back_rr_china.jpeg',
    buyLink: '',
    modalID: 'msQRcode',
    title: '【菲首】普版',
    brand: ['MS'],
    hit: [],
    descLink: '',
    price: '¥ 69',
    shipping: 'back',
    onlyFelix: false,
    allVersion: false,
    ribbon: '',
    fansite: 'china',
  },
  {
    id: 'ms_back_rr_ms_china',
    ver: ['rr'],
    image: './images/item/china/ms_back_rr_ms_china.jpeg',
    buyLink: '',
    modalID: 'msFelixQRcode',
    title: '【菲首】MS普版1+1',
    brand: ['MS'],
    hit: [],
    descLink: '',
    price: '¥ 138',
    shipping: 'back',
    onlyFelix: true,
    allVersion: false,
    ribbon: '',
    fansite: 'china',
  },
  // gem
  {
    id: 'ms_back_rr_gem',
    ver: ['rr'],
    image: './images/item/gem/ms_back_rr_gem.jpeg',
    buyLink: '',
    modalID: 'msQRcodeGem',
    title: '【宝石】普版',
    brand: ['MS'],
    hit: [],
    descLink: '',
    price: '¥ 69',
    shipping: 'back',
    onlyFelix: false,
    allVersion: false,
    ribbon: '',
    fansite: 'gem',
  },
  {
    id: 'ms_back_rr_ms_gem',
    ver: ['rr'],
    image: './images/item/gem/ms_back_rr_ms_gem.jpeg',
    buyLink: '',
    modalID: 'msFelixQRcodeGem',
    title: '【宝石】MS普版1+1',
    brand: ['MS'],
    hit: [],
    descLink: '',
    price: '¥ 138',
    shipping: 'back',
    onlyFelix: true,
    allVersion: false,
    ribbon: '',
    fansite: 'gem',
  },
]