const nanyiTitle = '楠艺';
const nanyiItems = [
  {
    id: 'ny-back-abc-ny-china',
    ver: ['abc'],
    image: './images/ny-back-abc_ny.jpg',
    buyLink: 'https://www.nanyiglobal.com/2305SKZNYLD-719261-0?continueFlag=407d506a7e76ce1b185a9a2faef09e43',
    title: '普版',
    brand: ['楠艺'],
    hit: [],
    descLink: '',
    price: '¥ 79',
    shipping: 'back',
    onlyFelix: false,
  },
  {
    id: 'ny-back-abc-4-china',
    ver: ['abc'],
    image: './images/nanyi.jpg',
    buyLink: 'https://www.nanyiglobal.com/2305skzpo2pb-5?continueFlag=407d506a7e76ce1b185a9a2faef09e43',
    title: '普版',
    brand: ['MS', 'WM', 'MMT', 'EL'],
    hit: [],
    descLink: '',
    price: '¥ 75~82',
    shipping: 'back',
    onlyFelix: false,
  },
  {
    id: 'ny-back-abc-6-china',
    ver: ['abc'],
    image: './images/nanyi.jpg',
    buyLink: 'https://www.nanyiglobal.com/2304SKZPOPB-752019-0?continueFlag=9c4cfd622c00702947e163aebf60dd92',
    title: '普版',
    brand: ['SW', 'YES24', 'MP', 'JYP', 'MK', 'BDM'],
    hit: [],
    descLink: '',
    price: '¥ 72~90',
    shipping: 'back',
    onlyFelix: false,
  },
  {
    id: 'ny-back-d-6-china',
    ver: ['d'],
    image: './images/nanyi.jpg',
    buyLink: 'https://www.nanyiglobal.com/2304SKZPODIG-528670-0?continueFlag=9c4cfd622c00702947e163aebf60dd92',
    title: 'D版',
    brand: ['SW', 'YES24', 'MP', 'JYP', 'MK', 'BDM'],
    hit: [],
    descLink: '',
    price: '¥ 49~60',
    shipping: 'back',
    onlyFelix: false,
  },
  {
    id: 'ny-back-abc-6-gem',
    ver: ['abc'],
    image: './images/nanyi-abc-gem.png',
    buyLink: 'https://www.nanyiglobal.com/2304enpodgeset-396206-0?continueFlag=55e456ec3bc9bcf0d27e8ecc80f8e10d',
    title: '普版',
    brand: ['SW', 'YES24', 'MP', 'JYP', 'MK', 'BDM'],
    hit: [],
    descLink: '',
    price: '¥ 72~90',
    shipping: 'back',
    onlyFelix: false,
  },
  {
    id: 'ny-back-d-6-gem',
    ver: ['d'],
    image: './images/nanyi-d-gem.png',
    buyLink: 'https://www.nanyiglobal.com/2304skzpopb-865349-0?continueFlag=55e456ec3bc9bcf0d27e8ecc80f8e10d',
    title: 'D版',
    brand: ['SW', 'YES24', 'MP', 'JYP', 'MK', 'BDM'],
    hit: [],
    descLink: '',
    price: '¥ 49~60',
    shipping: 'back',
    onlyFelix: false,
  },
]