const nanyiTitle = '楠艺';
const nanyiItems = [
  {
    id: 'ny_back_limit_china',
    ver: ['limit'],
    image: './images/item/ny_back_limit_china.jpeg',
    buyLink: 'https://www.nanyiglobal.com/2310skzlmtdpo-7',
    title: '',
    brand: ['YES24', 'MP', 'SW', 'ALD'],
    hit: [],
    descLink: '',
    price: '¥ 73~87',
    shipping: 'back',
    onlyFelix: false,
    ribbon: '',
  },
  {
    id: 'ny_back_rr_china',
    ver: ['rr'],
    image: './images/item/ny_back_rr_china.jpeg',
    buyLink: 'https://www.nanyiglobal.com/2310skzpbpo-9',
    title: '',
    brand: ['JYP', 'MK', 'YES24', 'MP', 'BDM', 'SW', 'ALD'],
    hit: [],
    descLink: '',
    price: '¥ 67.5~82.5',
    shipping: 'back',
    onlyFelix: false,
    ribbon: '',
  },
  {
    id: 'ny_back_p_china',
    ver: ['p'],
    image: './images/item/ny_back_p_china.jpeg',
    buyLink: 'https://www.nanyiglobal.com/2310skzpcpo-8',
    title: '',
    brand: ['JYP', 'MK', 'YES24', 'MP', 'BDM', 'SW', 'ALD'],
    hit: [],
    descLink: '',
    price: '¥ 49~60',
    shipping: 'back',
    onlyFelix: false,
    ribbon: '',
  },
  {
    id: 'ny_back_h_china',
    ver: ['h'],
    image: './images/item/ny_back_h_china.jpeg',
    buyLink: 'https://www.nanyiglobal.com/2310skzhpo-5',
    title: '',
    brand: ['JYP', 'MK', 'YES24', 'MP', 'BDM', 'SW', 'ALD'],
    hit: [],
    descLink: '',
    price: '¥ 49~60',
    shipping: 'back',
    onlyFelix: false,
    ribbon: '',
  },
]