const nanyiTitle = '楠艺';
const nanyiItems = [
  {
    id: 'ny_back_limit_china',
    ver: ['limit'],
    image: './images/item/china/ny_back_limit_china.jpeg',
    buyLink: 'https://www.nanyiglobal.com/2310skzlmtdpo-7',
    title: '【菲首】限量版',
    brand: ['YES24', 'MP', 'SW', '阿拉丁'],
    hit: [],
    descLink: '',
    price: '¥ 73~87',
    shipping: 'back',
    onlyFelix: false,
    allVersion: false,
    ribbon: '',
    fansite: 'china',
  },
  {
    id: 'ny_back_rr_china',
    ver: ['rr'],
    image: './images/item/china/ny_back_rr_china.jpeg',
    buyLink: 'https://www.nanyiglobal.com/2310skzpbpo-9',
    title: '【菲首】普版',
    brand: ['JYP', 'MK', 'YES24', 'MP', 'BDM', 'SW', '阿拉丁', 'WM', 'MMT'],
    hit: [],
    descLink: '',
    price: '¥ 67.5~82.5',
    shipping: 'back',
    onlyFelix: false,
    allVersion: false,
    ribbon: '',
    fansite: 'china',
  },
  {
    id: 'ny_back_p_china',
    ver: ['p'],
    image: './images/item/china/ny_back_p_china.jpeg',
    buyLink: 'https://www.nanyiglobal.com/2310skzpcpo-8',
    title: '【菲首】P版',
    brand: ['JYP', 'MK', 'YES24', 'MP', 'BDM', 'SW', '阿拉丁'],
    hit: [],
    descLink: '',
    price: '¥ 49~60',
    shipping: 'back',
    onlyFelix: false,
    allVersion: false,
    ribbon: '',
    fansite: 'china',
  },
  {
    id: 'ny_back_h_china',
    ver: ['h'],
    image: './images/item/china/ny_back_h_china.jpeg',
    buyLink: 'https://www.nanyiglobal.com/2310skzhpo-5',
    title: '【菲首】H版',
    brand: ['JYP', 'MK', 'YES24', 'MP', 'BDM', 'SW', '阿拉丁'],
    hit: [],
    descLink: '',
    price: '¥ 49~60',
    shipping: 'back',
    onlyFelix: false,
    allVersion: false,
    ribbon: '',
    fansite: 'china',
  },
  {
    id: 'ny_back_rr_mk_china',
    ver: ['rr'],
    image: './images/item/china/ny_back_rr_mk_china.jpeg',
    buyLink: 'https://www.nanyiglobal.com/2310skzmkpb11set-2-62722853',
    title: '【菲首】MK普版1+1',
    brand: ['MK'],
    hit: [],
    descLink: '',
    price: '¥ 154',
    shipping: 'back',
    onlyFelix: true,
    ribbon: '',
    fansite: 'china',
    soldOut: true,
  },
  // gem
  {
    id: 'ny_back_limit_gem',
    ver: ['limit'],
    image: './images/item/gem/ny_back_limit_gem.jpeg',
    buyLink: 'https://www.nanyiglobal.com/2310skzlmtdpo-1',
    title: '【宝石】限量版',
    brand: ['YES24', 'MP', 'SW', '阿拉丁'],
    hit: [],
    descLink: '',
    price: '¥ 73~87',
    shipping: 'back',
    onlyFelix: false,
    allVersion: false,
    ribbon: '',
    fansite: 'gem',
  },
  {
    id: 'ny_back_rr_gem',
    ver: ['rr'],
    image: './images/item/gem/ny_back_rr_gem.jpeg',
    buyLink: 'https://www.nanyiglobal.com/2310skzpbpo-10',
    title: '【宝石】普版',
    brand: ['JYP', 'MK', 'YES24', 'MP', 'BDM', 'SW', '阿拉丁'],
    hit: [],
    descLink: '',
    price: '¥ 67.5~82.5',
    shipping: 'back',
    onlyFelix: false,
    allVersion: false,
    ribbon: '',
    fansite: 'gem',
  },
  {
    id: 'ny_back_p_gem',
    ver: ['p'],
    image: './images/item/gem/ny_back_p_gem.jpeg',
    buyLink: 'https://www.nanyiglobal.com/2310skzpcpo-9',
    title: '【宝石】P版',
    brand: ['JYP', 'MK', 'YES24', 'MP', 'BDM', 'SW', '阿拉丁'],
    hit: [],
    descLink: '',
    price: '¥ 49~60',
    shipping: 'back',
    onlyFelix: false,
    allVersion: false,
    ribbon: '',
    fansite: 'gem',
  },
  {
    id: 'ny_back_h_gem',
    ver: ['h'],
    image: './images/item/gem/ny_back_h_gem.jpeg',
    buyLink: 'https://www.nanyiglobal.com/2310skzhpo-6',
    title: '【宝石】H版',
    brand: ['JYP', 'MK', 'YES24', 'MP', 'BDM', 'SW', '阿拉丁'],
    hit: [],
    descLink: '',
    price: '¥ 49~60',
    shipping: 'back',
    onlyFelix: false,
    allVersion: false,
    ribbon: '',
    fansite: 'gem',
  },
]