const nonBackItems = [
  {
    id: 'non-back-abc-d-k4-sr-bdn-kms-el-am-china',
    ver: ['abc', 'd'],
    image: './images/wd-non-back-abc_k4_sr_bdn_kms_el_am.jpg',
    buyLink: 'https://weidian.com/item.html?itemID=6281053074&wfr=c',
    title: '拆卡一键毕业',
    brand: ['K4', 'BDN', '星河', 'KMS', 'EL', 'AM'],
    hit: ['李龙馥特典卡 * 6'],
    descLink: 'https://weibo.com/6375947740/MFaNztLxJ',
    price: '¥ 429',
    shipping: 'non-back',
    onlyFelix: true,
  },
  {
    id: 'wd-non-back-abc-el-bdn',
    ver: ['abc'],
    image: './images/wd-non-back-abc-el-bdn.jpg',
    buyLink: 'https://weidian.com/item.html?itemID=6294359876&wfr=c&ifr=itemdetail&source=goods_home&sfr=app&continueFlag=8b2f5b9fc81d43482ebf8f9ccb463426',
    title: '普版拆卡 1+1',
    brand: ['EL', 'BDN'],
    hit: ['可指定成员EL特典卡', '可指定成员BDN特典卡'],
    descLink: 'https://weibo.com/5947554719/MFTuPqXtN',
    price: '¥ 169',
    shipping: 'non-back',
    onlyFelix: true,
  },
  {
    id: 'non-back-abc-d-specify-collection-china',
    ver: ['abc', 'd'],
    image: './images/non-back-abc-d-specify-collection-china.jpg',
    buyLink: 'https://weidian.com/item.html?itemID=6282545647&wfr=c',
    title: '拆卡可指定成员合集',
    brand: ['BDN', 'EL', 'KMS', '星河', 'K4'],
    hit: ['可指定成员特典卡'],
    descLink: 'https://weibo.com/6375947740/MFjiGhr8s',
    price: '¥ 46+',
    shipping: 'non-back',
    onlyFelix: true,
  },
  {
    id: 'non-back-abc-d-collection-china',
    ver: ['abc', 'd'],
    image: './images/non-back-abc-d-collection-china.jpg',
    buyLink: 'https://weidian.com/item.html?itemID=6282506005&wfr=c',
    title: '拆卡合集',
    brand: ['MK', 'MP', 'BDM', 'SW', 'JYP', 'MMT', 'WM', 'MS', 'AM'],
    hit: [],
    descLink: 'https://weibo.com/6375947740/MFjiGhr8s',
    price: '¥ 46+',
    shipping: 'non-back',
    onlyFelix: false,
  },
  {
    id: 'non-back-abc-kms-event-gem',
    ver: ['abc'],
    image: './images/non-back-abc-kms-event-gem.jpg',
    buyLink: 'https://weidian.com/item.html?itemID=6284957745&spider_token=8157',
    title: '敷敷宝袋 拆卡活动',
    brand: ['KMS'],
    hit: [],
    descLink: 'https://weibo.com/5947554719/MFrhK0JAr',
    price: '¥ 96+',
    shipping: 'non-back',
    onlyFelix: true,
  },
  {
    id: 'non-back-abc-am-china',
    ver: ['abc'],
    image: './images/non-back-abc-am-china.jpg',
    buyLink: 'http://m.liveonepick.com/#/?productId=4f9d197c261e4496a58016c54be05853&continueFlag=d8749e22f08e5d90f3fc4264f2505e49',
    title: '普版拆卡',
    brand: ['AM'],
    hit: ['可指定成员AM特典卡'],
    descLink: 'https://weibo.com/6375947740/MFCN5nFmL',
    price: '¥ 64.5',
    shipping: 'non-back',
    onlyFelix: true,
  },
  {
    id: 'non-back-abc-kms-el-china',
    ver: ['abc'],
    image: './images/non-back-abc-kms-el-china.jpg',
    buyLink: 'https://weidian.com/item.html?itemID=6286154649&wfr=c',
    title: 'KMS+EL拆卡',
    brand: ['KMS', 'EL'],
    hit: ['可指定成员KMS特典卡', '可指定成员EL特典卡'],
    descLink: 'https://weibo.com/6375947740/MFuGuzyB4',
    price: '¥ 112',
    shipping: 'non-back',
    onlyFelix: true,
  },
  {
    id: 'non-back-abc-el-china',
    ver: ['abc'],
    image: './images/wd-non-back-abc_el.jpg',
    buyLink: 'https://weidian.com/item.html?itemID=6280658681&wfr=c',
    title: '普版拆卡',
    brand: ['EL'],
    hit: ['可指定成员EL特典卡'],
    descLink: 'https://weibo.com/6375947740/MFcrw4rTf',
    price: '¥ 88.5',
    shipping: 'non-back',
    onlyFelix: true,
  },
  {
    id: 'non-back-abc-sr-china-1',
    ver: ['abc'],
    image: './images/sr-non-back-abc_sr-1.jpg',
    buyLink: 'http://m.liveonepick.com/#/?productId=db9a7539568e43fbb8390b3cb4f4d76f&continueFlag=bd4fddecd5a8db3ad9503af53320e97c',
    title: '普版拆卡',
    brand: ['星河'],
    hit: ['可指定成员星河特典卡'],
    descLink: 'https://weibo.com/6375947740/MF8JV0dKo',
    price: '¥ 64.5',
    shipping: 'non-back',
    onlyFelix: true,
  },
  {
    id: 'non-back-abc-kms-china-1',
    ver: ['abc'],
    image: './images/wd-non-back_kms-1.jpg',
    buyLink: 'https://weidian.com/item.html?itemID=6276793979&wfr=c&ifr=itemdetail&source=goods_home&sfr=app&continueFlag=407d506a7e76ce1b185a9a2faef09e43',
    title: '普版拆卡',
    brand: ['KMS'],
    hit: ['可指定成员KMS特典卡'],
    descLink: 'https://weibo.com/5947554719/MF0p15V5o',
    price: '¥ 81',
    shipping: 'non-back',
    onlyFelix: true,
  },
  {
    id: 'k4-non-back-abc-k4-china',
    ver: ['abc'],
    image: './images/k4-abc.jpg',
    buyLink: 'https://cn.ktown4u.com/iteminfo?grp_no=1742515&fanc_goods_no=207585&goods_no=92375',
    title: '普版拆卡',
    brand: ['K4'],
    hit: ['可指定成员特典卡'],
    descLink: 'https://weibo.com/6375947740/MEXVsmMT3',
    price: '¥ 64.5',
    shipping: 'non-back',
    onlyFelix: true,
  },
  {
    id: 'k4-non-back-d-k4-china',
    ver: ['d'],
    image: './images/k4-d.jpg',
    buyLink: 'https://cn.ktown4u.com/iteminfo?grp_no=1742515&fanc_goods_no=207586&goods_no=92375',
    title: 'D版拆卡',
    brand: ['K4'],
    hit: ['可指定成员特典卡'],
    descLink: 'https://weibo.com/6375947740/MEXVsmMT3',
    price: '¥ 44',
    shipping: 'non-back',
    onlyFelix: true,
  },
  {
    id: 'non-back-abc-k4-gem',
    ver: ['abc'],
    image: './images/k4-non-back_k4-gem.jpg',
    buyLink: 'https://weidian.com/item.html?itemID=6264236457&wfr=c&ifr=itemdetail&source=goods_home&sfr=app&continueFlag=55e456ec3bc9bcf0d27e8ecc80f8e10d',
    title: '普版拆卡',
    brand: ['K4'],
    hit: ['可指定成员特典卡'],
    descLink: 'https://weibo.com/5947554719/ME5B52yLe',
    price: '¥ 64.5',
    shipping: 'non-back',
    onlyFelix: false,
  },
  {
    id: 'non-back-abc-ny-china',
    ver: ['abc'],
    image: './images/wd-non-back-abc_ny.jpg',
    buyLink: 'https://weidian.com/item.html?itemID=6277804320&wfr=c',
    title: '普版拆卡',
    brand: ['楠艺'],
    hit: ['随机成员楠艺特典卡'],
    descLink: 'https://weibo.com/6375947740/MF01Uy5ED',
    price: '¥ 76',
    shipping: 'non-back',
    onlyFelix: false,
  },
  {
    id: 'non-back-abc-sr-china-2',
    ver: ['abc'],
    image: './images/sr-non-back-abc_sr-2.jpg',
    buyLink: 'http://m.liveonepick.com/#/?productId=ad9d8d41cb894fa0a76e8a5ed39d6dcb&continueFlag=407d506a7e76ce1b185a9a2faef09e43',
    title: '普版拆卡',
    brand: ['星河'],
    hit: ['随机成员星河特典卡'],
    descLink: 'https://weibo.com/6375947740/MEZQHiQSz"',
    price: '¥ 64.5',
    shipping: 'non-back',
    onlyFelix: false,
  },
  {
    id: 'non-back-abc-yzy-china',
    ver: ['abc'],
    image: './images/wd-non-back_yzy.jpg',
    buyLink: 'https://weidian.com/item.html?itemID=6275854956&wfr=c',
    title: '普版拆卡',
    brand: ['一直娱'],
    hit: ['随机成员一直娱特典卡'],
    descLink: 'https://weibo.com/6375947740/MESoewdfA',
    price: '¥ 81',
    shipping: 'non-back',
    onlyFelix: false,
  },
  {
    id: 'non-back-abc-am-china',
    ver: ['abc'],
    image: './images/sr-non-back_am.jpg',
    buyLink: 'http://m.liveonepick.com/#/?productId=c9f4edca6b5340b4a4b1ddc2d3b6cded&continueFlag=89512eeeb5e9b2e411288376fc65ea57',
    title: '普版拆卡 1+1',
    brand: ['AM'],
    hit: ['李龙馥AM特典卡', '随机成员AM特典卡'],
    descLink: 'https://weibo.com/6375947740/MEdvxw7xg',
    price: '¥ 88~129',
    shipping: 'non-back',
    onlyFelix: true,
  },
  {
    id: 'non-back-abc-bdm-china',
    ver: ['abc'],
    image: './images/bdm-non-back-abc.jpg',
    buyLink: 'https://weidian.com/item.html?itemID=6269519990&wfr=c',
    title: '普版拆卡',
    brand: ['BDM'],
    hit: ['李龙馥指定特典卡 (不一定BDM)', '随机成员BDM特典卡'],
    descLink: 'https://weibo.com/6375947740/MEnpr08xJ',
    price: '¥ 100',
    shipping: 'non-back',
    onlyFelix: false,
  },
  {
    id: 'non-back-abc-yes24-gem',
    ver: ['abc'],
    image: './images/yes24-event.jpg',
    buyLink: 'https://weidian.com/item.html?itemID=6266724291&spider_token=8e9d',
    title: '普版拆卡',
    brand: ['YES24'],
    hit: ['李龙馥指定特典卡 (不一定YES24)', '随机成员YES24特典卡'],
    descLink: 'https://weibo.com/5947554719/MEeWFy77a',
    price: '¥ 96',
    shipping: 'non-back',
    onlyFelix: false,
  },
  {
    id: 'non-back-abc-sw-gem',
    ver: ['abc'],
    image: './images/sw-event.jpg',
    buyLink: 'https://weidian.com/item.html?itemID=6267455598&spider_token=acab',
    title: '普版拆卡',
    brand: ['SW'],
    hit: ['李龙馥指定特典卡 (不一定SW)', '随机成员SW特典卡'],
    descLink: 'https://weibo.com/5947554719/MEe7FxOi5',
    price: '¥ 88',
    shipping: 'non-back',
    onlyFelix: false,
  },
  {
    id: 'non-back-abc-mp-gem',
    ver: ['abc'],
    image: './images/mp-event.jpg',
    buyLink: 'https://weidian.com/item.html?itemID=6266601673&spider_token=c797',
    title: '普版拆卡',
    brand: ['MP'],
    hit: ['李龙馥指定特典卡 (不一定MP)', '随机成员MP特典卡'],
    descLink: 'hhttps://weibo.com/5947554719/MEenw2uCE',
    price: '¥ 100',
    shipping: 'non-back',
    onlyFelix: false,
  },
  {
    id: 'non-back-abc-yzy-gem',
    ver: ['abc'],
    image: './images/wd-non-back_yzy-gem.jpg',
    buyLink: 'https://weidian.com/item.html?itemID=6276073366&wfr=c&ifr=itemdetail&source=goods_home&sfr=app&continueFlag=407d506a7e76ce1b185a9a2faef09e43',
    title: '普版拆卡 2+2',
    brand: ['一直娱'],
    hit: ['黄铉辰+李旻浩', '黄铉辰+金昇玟', '金昇玟+李旻浩', '李旻浩+韩知城', '随机成员一直娱特典卡 * 2'],
    descLink: 'https://weibo.com/5947554719/METq97wDz',
    price: '¥ 326',
    shipping: 'non-back',
    onlyFelix: false,
  },
]