const oxbldkrTitle = '偶像便利店';
const oxbldkrItems = [
  {
    id: 'oxbldkr-back-abc-3-china',
    ver: ['abc'],
    image: './images/oxbldkr.jpeg',
    buyLink: 'https://www.oxbldkr.com/index.php/wap/goods/detail?goods_id=1256&continueFlag=89512eeeb5e9b2e411288376fc65ea57',
    title: '普版',
    brand: ['SW', 'MP', 'MK'],
    hit: ['3本一套无特典', '8本一套有特典'],
    descLink: '',
    price: 'RMB 245+',
    shipping: 'back',
    onlyFelix: false,
  },
  {
    id: 'oxbldkr-back-d-3-china',
    ver: ['d'],
    image: './images/oxbldkr.jpeg',
    buyLink: 'https://www.oxbldkr.com/index.php/wap/goods/detail?goods_id=1256&continueFlag=89512eeeb5e9b2e411288376fc65ea57',
    title: 'D版',
    brand: ['SW', 'MP', 'MK'],
    hit: ['8本一套无特典', '8本一套有特典'],
    descLink: '',
    price: 'RMB 415+',
    shipping: 'back',
    onlyFelix: false,
  },
  {
    id: 'oxbldkr-back-abc-3-gem',
    ver: ['abc'],
    image: './images/oxbldkr-gem.jpeg',
    buyLink: 'https://www.oxbldkr.com/index.php/wap/goods/detail?goods_id=1257&continueFlag=55e456ec3bc9bcf0d27e8ecc80f8e10d',
    title: '普版',
    brand: ['SW', 'MP', 'MK'],
    hit: ['3本一套无特典', '8本一套有特典'],
    descLink: '',
    price: 'RMB 245+',
    shipping: 'back',
    onlyFelix: false,
  },
  {
    id: 'oxbldkr-back-d-3-gem',
    ver: ['d'],
    image: './images/oxbldkr-gem.jpeg',
    buyLink: 'https://www.oxbldkr.com/index.php/wap/goods/detail?goods_id=1257&continueFlag=55e456ec3bc9bcf0d27e8ecc80f8e10d',
    title: 'D版',
    brand: ['SW', 'MP', 'MK'],
    hit: ['8本一套无特典', '8本一套有特典'],
    descLink: '',
    price: 'RMB 415+',
    shipping: 'back',
    onlyFelix: false,
  },
  {
    id: 'oxbldkr-back-abc-ms-wm-el-china',
    ver: ['abc'],
    image: './images/oxbldkr-back-abc_ms_wm_el.png',
    buyLink: 'https://www.oxbldkr.com/index.php/wap/goods/detail?goods_id=1363&continueFlag=bd4fddecd5a8db3ad9503af53320e97c',
    title: '普版',
    brand: ['MS', 'WM', 'EL'],
    hit: ['8本一套有特典'],
    descLink: '',
    price: 'RMB 658+',
    shipping: 'back',
    onlyFelix: false,
  },
]