const oxbldkrTitle = '偶像便利店';
const oxbldkrItems = [
  {
    id: 'oxbldkr_back_limit_china',
    ver: ['limit'],
    image: './images/item/china/oxbldkr_back_limit_china.jpeg',
    buyLink: 'https://www.oxbldkr.com/index.php/wap/goods/detail?goods_id=7159',
    title: '【菲首】限量版 (1套8张)',
    brand: ['MP'],
    hit: [],
    descLink: '',
    price: '¥ 738',
    shipping: 'back',
    onlyFelix: false,
    allVersion: false,
    ribbon: '',
    fansite: 'china',
  },
  {
    id: 'oxbldkr_back_rr_wm_1_china',
    ver: ['rr'],
    image: './images/item/china/oxbldkr_back_rr_wm_1_china.jpeg',
    buyLink: 'https://www.oxbldkr.com/index.php/wap/goods/detail?goods_id=7889',
    title: '【菲首】普版',
    brand: ['WM'],
    hit: [],
    descLink: '',
    price: '¥ 77',
    shipping: 'back',
    onlyFelix: false,
    allVersion: false,
    ribbon: '',
    fansite: 'china',
  },
  {
    id: 'oxbldkr_back_rr_china',
    ver: ['rr'],
    image: './images/item/china/oxbldkr_back_rr_china.jpeg',
    buyLink: 'https://www.oxbldkr.com/index.php/wap/goods/detail?goods_id=7290',
    title: '【菲首】普版',
    brand: ['MK', 'YES24', '阿拉丁'],
    hit: [],
    descLink: '',
    price: '¥ 79~87',
    shipping: 'back',
    onlyFelix: false,
    allVersion: false,
    ribbon: '',
    fansite: 'china',
  },
  {
    id: 'oxbldkr_back_rr_1_china',
    ver: ['rr'],
    image: './images/item/china/oxbldkr_back_rr_1_china.jpeg',
    buyLink: 'https://www.oxbldkr.com/index.php/wap/goods/detail?goods_id=7292',
    title: '【菲首】普版 (2版)',
    brand: ['MK', 'YES24', '阿拉丁'],
    hit: [],
    descLink: '',
    price: '¥ 157~172',
    shipping: 'back',
    onlyFelix: false,
    allVersion: false,
    ribbon: '',
    fansite: 'china',
  },
  {
    id: 'oxbldkr_back_p_h_china',
    ver: ['p', 'h'],
    image: './images/item/china/oxbldkr_back_p_h_china.jpeg',
    buyLink: 'https://www.oxbldkr.com/index.php/wap/goods/detail?goods_id=7291',
    title: '【菲首】P版 / H版',
    brand: ['MK', 'YES24', '阿拉丁'],
    hit: [],
    descLink: '',
    price: '¥ 58~64',
    shipping: 'back',
    onlyFelix: false,
    allVersion: false,
    ribbon: '',
    fansite: 'china',
  },
  {
    id: 'oxbldkr_back_rr_wm_china',
    ver: ['rr'],
    image: './images/item/china/oxbldkr_back_rr_wm_china.jpeg',
    buyLink: 'https://www.oxbldkr.com/index.php/wap/goods/detail?goods_id=7890',
    title: '【菲首】普版 (1套8张)',
    brand: ['WM'],
    hit: [],
    descLink: '',
    price: '¥ 674',
    shipping: 'back',
    onlyFelix: false,
    allVersion: false,
    ribbon: '',
    fansite: 'china',
  },
  {
    id: 'oxbldkr_back_rr_p_h_china',
    ver: ['rr', 'p', 'h'],
    image: './images/item/china/oxbldkr_back_rr_p_h_china.jpeg',
    buyLink: 'https://www.oxbldkr.com/index.php/wap/goods/detail?goods_id=7293',
    title: '【菲首】普版 / P版 / H版 (1套8张)',
    brand: ['MK', 'YES24'],
    hit: [],
    descLink: '',
    price: '¥ 549~745',
    shipping: 'back',
    onlyFelix: false,
    allVersion: false,
    ribbon: '',
    fansite: 'china',
  },
  // gem
  {
    id: 'oxbldkr_back_rr_wm_1_gem',
    ver: ['rr'],
    image: './images/item/gem/oxbldkr_back_rr_wm_1_gem.jpeg',
    buyLink: 'https://www.oxbldkr.com/index.php/wap/goods/detail?goods_id=7901',
    title: '【菲首】普版',
    brand: ['WM'],
    hit: [],
    descLink: '',
    price: '¥ 77',
    shipping: 'back',
    onlyFelix: false,
    allVersion: false,
    ribbon: '',
    fansite: 'gem',
  },
  {
    id: 'oxbldkr_back_rr_gem',
    ver: ['rr'],
    image: './images/item/gem/oxbldkr_back_rr_gem.jpeg',
    buyLink: 'https://www.oxbldkr.com/index.php/wap/goods/detail?goods_id=7266',
    title: '【宝石】普版',
    brand: ['MK', 'YES24', '阿拉丁'],
    hit: [],
    descLink: '',
    price: '¥ 79~87',
    shipping: 'back',
    onlyFelix: false,
    allVersion: false,
    ribbon: '',
    fansite: 'gem',
  },
  {
    id: 'oxbldkr_back_rr_1_gem',
    ver: ['rr'],
    image: './images/item/gem/oxbldkr_back_rr_1_gem.jpeg',
    buyLink: 'https://www.oxbldkr.com/index.php/wap/goods/detail?goods_id=7268',
    title: '【宝石】普版 (2版)',
    brand: ['MK', 'YES24', '阿拉丁'],
    hit: [],
    descLink: '',
    price: '¥ 157~172',
    shipping: 'back',
    onlyFelix: false,
    allVersion: false,
    ribbon: '',
    fansite: 'gem',
  },
  {
    id: 'oxbldkr_back_p_h_gem',
    ver: ['p', 'h'],
    image: './images/item/gem/oxbldkr_back_p_h_gem.jpeg',
    buyLink: 'https://www.oxbldkr.com/index.php/wap/goods/detail?goods_id=7267',
    title: '【宝石】P版 / H版',
    brand: ['MK', 'YES24', '阿拉丁'],
    hit: [],
    descLink: '',
    price: '¥ 58~64',
    shipping: 'back',
    onlyFelix: false,
    allVersion: false,
    ribbon: '',
    fansite: 'gem',
  },
  {
    id: 'oxbldkr_back_rr_wm_gem',
    ver: ['rr'],
    image: './images/item/gem/oxbldkr_back_rr_wm_gem.jpeg',
    buyLink: 'https://www.oxbldkr.com/index.php/wap/goods/detail?goods_id=7902',
    title: '【菲首】普版 (1套8张)',
    brand: ['WM'],
    hit: [],
    descLink: '',
    price: '¥ 674',
    shipping: 'back',
    onlyFelix: false,
    allVersion: false,
    ribbon: '',
    fansite: 'gem',
  },
  {
    id: 'oxbldkr_back_rr_p_h_gem',
    ver: ['rr', 'p', 'h'],
    image: './images/item/gem/oxbldkr_back_rr_p_h_gem.jpeg',
    buyLink: 'https://www.oxbldkr.com/index.php/wap/goods/detail?goods_id=7269',
    title: '【宝石】普版 / P版 / H版 (1套8张)',
    brand: ['MK', 'YES24'],
    hit: [],
    descLink: '',
    price: '¥ 549~745',
    shipping: 'back',
    onlyFelix: false,
    allVersion: false,
    ribbon: '',
    fansite: 'gem',
  },
]