const recommendTitle = '推荐购买';
const recommendItems = [
  {
    id: 'k4-back-abc',
    ver: ['abc'],
    image: './images/k4-abc.jpg',
    buyLink: 'https://cn.ktown4u.com/iteminfo?grp_no=1741898&fanc_goods_no=207508&goods_no=94037',
    title: '普版 (随机版本)',
    brand: [],
    hit: [],
    descLink: '',
    price: '¥ 65.5',
    shipping: 'back',
    onlyFelix: false,
  },
  {
    id: 'k4-back-abc-3',
    ver: ['abc'],
    image: './images/k4-abc.jpg',
    buyLink: 'https://cn.ktown4u.com/iteminfo?grp_no=1741898&fanc_goods_no=207499&goods_no=94043',
    title: '普版 套装 (3本)',
    brand: [],
    hit: [],
    descLink: '',
    price: '¥ 196.5',
    shipping: 'back',
    onlyFelix: false,
  },
  {
    id: 'k4-back-d',
    ver: ['d'],
    image: './images/k4-d.jpg',
    buyLink: 'https://cn.ktown4u.com/iteminfo?grp_no=1741898&fanc_goods_no=207507&goods_no=94035',
    title: 'D版 (随机版本)',
    brand: [],
    hit: [],
    descLink: '',
    price: '¥ 45',
    shipping: 'back',
    onlyFelix: false,
  },
  {
    id: 'non-back-abc-d-k4-sr-bdn-kms-el-china',
    ver: ['abc', 'd'],
    image: './images/wd-non-back-abc_k4_sr_bdn_kms_el_am.jpg',
    buyLink: 'https://weidian.com/item.html?itemID=6281053074&wfr=c',
    title: '拆卡一键毕业',
    brand: ['K4', 'BDN', '星河', 'KMS', 'EL', 'AM'],
    hit: ['李龙馥特典卡 * 6'],
    descLink: 'https://weibo.com/6375947740/MFaNztLxJ',
    price: '¥ 429',
    shipping: 'non-back',
    onlyFelix: true,
  },
  {
    id: 'back-abc-kms-china',
    ver: ['abc'],
    image: './images/kram-back-abc_kms.jpg',
    buyLink: 'https://shop1382036085.v.weidian.com/item.html?itemID=6277672764&wfr=c&ifr=itemdetail&source=goods_home&sfr=app&continueFlag=407d506a7e76ce1b185a9a2faef09e43',
    title: '普版',
    brand: ['KMS'],
    hit: [],
    descLink: 'https://weibo.com/6375947740/MF0my4fKS',
    price: '¥ 80+',
    shipping: 'back',
    onlyFelix: false,
  }
]