const recommendTitle = '推荐购买';
const recommendItems = [
  {
    id: 'k4-back-abc',
    ver: ['abc'],
    image: './images/k4-abc.jpg',
    buyLink: 'https://cn.ktown4u.com/iteminfo?grp_no=1741898&fanc_goods_no=207508&goods_no=94037',
    title: '普版 (随机版本)',
    brand: [],
    hit: [],
    descLink: '',
    price: '¥ 65.5',
    shipping: 'back',
    onlyFelix: false,
  },
  {
    id: 'k4-back-abc-3',
    ver: ['abc'],
    image: './images/k4-abc.jpg',
    buyLink: 'https://cn.ktown4u.com/iteminfo?grp_no=1741898&fanc_goods_no=207499&goods_no=94043',
    title: '普版 套装 (3本)',
    brand: [],
    hit: [],
    descLink: '',
    price: '¥ 196.5',
    shipping: 'back',
    onlyFelix: false,
  },
  {
    id: 'k4-back-d',
    ver: ['d'],
    image: './images/k4-d.jpg',
    buyLink: 'https://cn.ktown4u.com/iteminfo?grp_no=1741898&fanc_goods_no=207507&goods_no=94035',
    title: 'D版 (随机版本)',
    brand: [],
    hit: [],
    descLink: '',
    price: '¥ 45',
    shipping: 'back',
    onlyFelix: false,
  },
  {
    id: 'non-back-abc-d-k4-sr-bdn-kms-el-china',
    ver: ['abc', 'd'],
    image: './images/wd-non-back-abc_k4_sr_bdn_kms_el_am.jpg',
    buyLink: 'https://weidian.com/item.html?itemID=6345515578&wfr=c',
    title: '拆卡一键毕业',
    brand: ['K4', 'BDN', '星河', 'KMS', 'EL', 'AM'],
    hit: ['李龙馥特典卡 * 5', '李龙馥KMS特典卡'],
    descLink: '',
    price: '¥ 345 / ¥ 45',
    shipping: 'non-back',
    onlyFelix: true,
  }
]