const srTitle = '星河';
const srItems = [
  {
    id: 'sr_back_limit_china',
    ver: ['limit'],
    image: './images/item/china/sr_back_limit_china.jpeg',
    buyLink: 'http://m.liveonepick.com/#/?productId=24bb74615a994e94892d270fdb239287',
    title: '',
    brand: [],
    hit: [],
    descLink: '',
    price: '¥ 63',
    shipping: 'back',
    onlyFelix: false,
    ribbon: '',
    fansite: 'china',
  },
  {
    id: 'sr_back_rr_china',
    ver: ['rr'],
    image: './images/item/china/sr_back_rr_china.jpeg',
    buyLink: 'http://m.liveonepick.com/#/?productId=0869b598a92e4ba5a2eb4f70b705752a',
    title: '',
    brand: [],
    hit: [],
    descLink: '',
    price: '¥ 63',
    shipping: 'back',
    onlyFelix: false,
    ribbon: '',
    fansite: 'china',
  },
  {
    id: 'sr_back_p_china',
    ver: ['p'],
    image: './images/item/china/sr_back_p_china.jpeg',
    buyLink: 'http://m.liveonepick.com/#/?productId=e36a344e8305489ca5c8588afafab3da',
    title: '',
    brand: [],
    hit: [],
    descLink: '',
    price: '¥ 46',
    shipping: 'back',
    onlyFelix: false,
    ribbon: '',
    fansite: 'china',
  },
  {
    id: 'sr_back_p_1_china',
    ver: ['p'],
    image: './images/item/china/sr_back_p_1_china.jpeg',
    buyLink: 'http://m.liveonepick.com/#/?productId=8d5eeb85c2b44865998b5ec3b7c5ef56',
    title: '',
    brand: [],
    hit: [],
    descLink: '',
    price: '¥ 46',
    shipping: 'back',
    onlyFelix: true,
    ribbon: '',
    fansite: 'china',
  },
  {
    id: 'sr_back_h_china',
    ver: ['h'],
    image: './images/item/china/sr_back_h_china.jpeg',
    buyLink: 'http://m.liveonepick.com/#/?productId=a81d5b7a5a9b45fe85db3f9344f6caed',
    title: '',
    brand: [],
    hit: [],
    descLink: '',
    price: '¥ 46',
    shipping: 'back',
    onlyFelix: false,
    ribbon: '',
    fansite: 'china',
  },
  // gem
  {
    id: 'sr_back_limit_gem',
    ver: ['limit'],
    image: './images/item/gem/sr_back_limit_gem.jpeg',
    buyLink: 'http://m.liveonepick.com/#/?productId=a1706ad5906844a78149917c627b0cff',
    title: '',
    brand: [],
    hit: [],
    descLink: '',
    price: '¥ 63',
    shipping: 'back',
    onlyFelix: false,
    ribbon: '',
    fansite: 'gem',
  },
  {
    id: 'sr_back_rr_gem',
    ver: ['rr'],
    image: './images/item/gem/sr_back_rr_gem.jpeg',
    buyLink: 'http://m.liveonepick.com/#/?productId=08050f76379241eea0399b02f37841f2',
    title: '',
    brand: [],
    hit: [],
    descLink: '',
    price: '¥ 63',
    shipping: 'back',
    onlyFelix: false,
    ribbon: '',
    fansite: 'gem',
  },
  {
    id: 'sr_back_p_gem',
    ver: ['p'],
    image: './images/item/gem/sr_back_p_gem.jpeg',
    buyLink: 'http://m.liveonepick.com/#/?productId=46680cbe4643480b8c9a16c297110469',
    title: '',
    brand: [],
    hit: [],
    descLink: '',
    price: '¥ 46',
    shipping: 'back',
    onlyFelix: false,
    ribbon: '',
    fansite: 'gem',
  },
  {
    id: 'sr_back_h_gem',
    ver: ['h'],
    image: './images/item/gem/sr_back_h_gem.jpeg',
    buyLink: 'http://m.liveonepick.com/#/?productId=50d96d2bbe0a499db4e1fe2896b13a4a',
    title: '',
    brand: [],
    hit: [],
    descLink: '',
    price: '¥ 46',
    shipping: 'back',
    onlyFelix: false,
    ribbon: '',
    fansite: 'gem',
  }, 
]