const srTitle = '星河';
const srItems = [
  {
    id: 'sr_back_limit_china',
    ver: ['limit'],
    image: './images/item/sr_back_limit_china.jpeg',
    buyLink: 'http://m.liveonepick.com/#/?productId=24bb74615a994e94892d270fdb239287',
    title: '',
    brand: [],
    hit: [],
    descLink: '',
    price: '¥ 63',
    shipping: 'back',
    onlyFelix: false,
    ribbon: '',
  },
  {
    id: 'sr_back_rr_china',
    ver: ['rr'],
    image: './images/item/sr_back_rr_china.jpeg',
    buyLink: 'http://m.liveonepick.com/#/?productId=0869b598a92e4ba5a2eb4f70b705752a',
    title: '',
    brand: [],
    hit: [],
    descLink: '',
    price: '¥ 63',
    shipping: 'back',
    onlyFelix: false,
    ribbon: '',
  },
  {
    id: 'sr_back_p_china',
    ver: ['p'],
    image: './images/item/sr_back_p_china.jpeg',
    buyLink: 'http://m.liveonepick.com/#/?productId=e36a344e8305489ca5c8588afafab3da',
    title: '',
    brand: [],
    hit: [],
    descLink: '',
    price: '¥ 46',
    shipping: 'back',
    onlyFelix: false,
    ribbon: '',
  },
  {
    id: 'sr_back_p_1_china',
    ver: ['p'],
    image: './images/item/sr_back_p_1_china.jpeg',
    buyLink: 'http://m.liveonepick.com/#/?productId=8d5eeb85c2b44865998b5ec3b7c5ef56',
    title: '',
    brand: [],
    hit: [],
    descLink: '',
    price: '¥ 46',
    shipping: 'back',
    onlyFelix: true,
    ribbon: '',
  },
  {
    id: 'sr_back_h_china',
    ver: ['h'],
    image: './images/item/sr_back_h_china.jpeg',
    buyLink: 'http://m.liveonepick.com/#/?productId=a81d5b7a5a9b45fe85db3f9344f6caed',
    title: '',
    brand: [],
    hit: [],
    descLink: '',
    price: '¥ 46',
    shipping: 'back',
    onlyFelix: false,
    ribbon: '',
  },
]