const wdTitle = 'KR-AM音像店 / 微店';
const wdItems = [
  {
    id: 'wd-back-abc-el-china',
    ver: ['abc'],
    image: './images/kram-back-abc_el.jpg',
    buyLink: 'https://shop1382036085.v.weidian.com/item.html?itemID=6280587181',
    title: '普版',
    brand: ['EL'],
    hit: ['指定李龙馥', '李龙馥1+1'],
    descLink: 'https://weibo.com/6375947740/MFcrw4rTf',
    price: 'RMB 88+',
    shipping: 'back',
    onlyFelix: true,
  },
  {
    id: 'wd-back-abc-bdn-china',
    ver: ['abc'],
    image: './images/wd-bandina.jpg',
    buyLink: 'https://weidian.com/item.html?itemID=6277651010&wfr=c',
    title: '普版',
    brand: ['BDN'],
    hit: ['可指定成员特典卡'],
    descLink: '',
    price: 'RMB 85.5',
    shipping: 'back',
    onlyFelix: false,
  },
  {
    id: 'kram-back-abc-kms-china',
    ver: ['abc'],
    image: './images/kram-back-abc_kms.jpg',
    buyLink: 'https://shop1382036085.v.weidian.com/item.html?itemID=6277672764&wfr=c&ifr=itemdetail&source=goods_home&sfr=app&continueFlag=407d506a7e76ce1b185a9a2faef09e43',
    title: '普版',
    brand: ['KMS'],
    hit: [],
    descLink: 'https://weibo.com/6375947740/MF0my4fKS',
    price: 'RMB 80+',
    shipping: 'back',
    onlyFelix: false,
  },
  {
    id: 'kram-back-abc-kms-gem',
    ver: ['abc'],
    image: './images/kram-back-abc_kms-gem.jpg',
    buyLink: 'https://shop1382036085.v.weidian.com/item.html?itemID=6276789639&wfr=c&ifr=itemdetail&source=goods_home&sfr=app&continueFlag=bd4fddecd5a8db3ad9503af53320e97c',
    title: '普版',
    brand: ['KMS'],
    hit: [],
    descLink: 'https://weibo.com/5947554719/MF0PkhfvQ',
    price: 'RMB 80+',
    shipping: 'back',
    onlyFelix: false,
  }
]