const wdChinaTitle = '菲首微店';
const wdChinaItems = [
  {
    id: 'wd_back_mp_china',
    ver: ['limit'],
    image: './images/item/china/wd_back_mp_china.jpeg',
    buyLink: 'https://weidian.com/item.html?itemID=6680452186',
    title: '',
    brand: ['MP'],
    hit: [],
    descLink: '',
    price: '¥ 87',
    shipping: 'back',
    onlyFelix: false,
    allVersion: false,
    ribbon: '',
    fansite: 'china',
  },
  {
    id: 'wd_back_mk_china',
    ver: ['limit'],
    image: './images/item/china/wd_back_mk_china.jpeg',
    buyLink: 'https://weidian.com/item.html?itemID=6680549007',
    title: '',
    brand: ['MK'],
    hit: [],
    descLink: '',
    price: '¥ 87',
    shipping: 'back',
    onlyFelix: false,
    allVersion: false,
    ribbon: '',
    fansite: 'china',
  },
  {
    id: 'wd_back_sw_china',
    ver: ['limit'],
    image: './images/item/china/wd_back_sw_china.jpeg',
    buyLink: 'https://weidian.com/item.html?itemID=6681334942',
    title: '',
    brand: ['SW'],
    hit: [],
    descLink: '',
    price: '¥ 80',
    shipping: 'back',
    onlyFelix: false,
    allVersion: false,
    ribbon: '',
    fansite: 'china',
  },
  {
    id: 'wd_back_bdm_china',
    ver: ['limit'],
    image: './images/item/china/wd_back_bdm_china.jpeg',
    buyLink: 'https://weidian.com/item.html?itemID=6681867256',
    title: '',
    brand: ['BDM'],
    hit: [],
    descLink: '',
    price: '¥ 87',
    shipping: 'back',
    onlyFelix: false,
    allVersion: false,
    ribbon: '',
    fansite: 'china',
  },
  {
    id: 'wd_non_back_target_china',
    ver: [''],
    image: './images/item/china/wd_non_back_target_china.jpeg',
    buyLink: 'https://weidian.com/item.html?itemID=6680825683',
    title: '',
    brand: ['美网TARGET'],
    hit: [],
    descLink: '',
    price: '¥ 209',
    shipping: 'non-back',
    onlyFelix: false,
    allVersion: false,
    ribbon: '',
    fansite: 'china',
  },
  {
    id: 'wd_non_back_bn_china',
    ver: [''],
    image: './images/item/china/wd_non_back_bn_china.jpeg',
    buyLink: 'https://weidian.com/item.html?itemID=6679476001',
    title: '',
    brand: ['美网BN'],
    hit: ['BN特典书签'],
    descLink: '',
    price: '¥ 253',
    shipping: 'non-back',
    onlyFelix: false,
    allVersion: false,
    ribbon: '',
    fansite: 'china',
  },
]