const wdChinaTitle = '菲首微店';
const wdChinaItems = [
  {
    id: 'wd_back_mp_china',
    ver: ['limit'],
    image: './images/item/china/wd_back_mp_china.jpeg',
    buyLink: 'https://weidian.com/item.html?itemID=6680452186',
    title: '【菲首】MP限量版',
    brand: ['MP'],
    hit: [],
    descLink: '',
    price: '¥ 87',
    shipping: 'back',
    onlyFelix: false,
    allVersion: false,
    ribbon: '',
    fansite: 'china',
  },
  {
    id: 'wd_back_mk_china',
    ver: ['limit'],
    image: './images/item/china/wd_back_mk_china.jpeg',
    buyLink: 'https://weidian.com/item.html?itemID=6680549007',
    title: '【菲首】MK限量版',
    brand: ['MK'],
    hit: [],
    descLink: '',
    price: '¥ 87',
    shipping: 'back',
    onlyFelix: false,
    allVersion: false,
    ribbon: '',
    fansite: 'china',
    soldOut: true,
  },
  {
    id: 'wd_back_sw_china',
    ver: ['limit'],
    image: './images/item/china/wd_back_sw_china.jpeg',
    buyLink: 'https://weidian.com/item.html?itemID=6681334942',
    title: '【菲首】SW限量版',
    brand: ['SW'],
    hit: [],
    descLink: '',
    price: '¥ 80',
    shipping: 'back',
    onlyFelix: false,
    allVersion: false,
    ribbon: '',
    fansite: 'china',
    soldOut: false,
  },
  {
    id: 'wd_back_bdm_china',
    ver: ['limit'],
    image: './images/item/china/wd_back_bdm_china.jpeg',
    buyLink: 'https://weidian.com/item.html?itemID=6681867256',
    title: '【菲首】BDM限量版',
    brand: ['BDM'],
    hit: [],
    descLink: '',
    price: '¥ 87',
    shipping: 'back',
    onlyFelix: false,
    allVersion: false,
    ribbon: '',
    fansite: 'china',
  },
  {
    id: 'wd_non_back_el_china',
    ver: ['rr'],
    image: './images/item/china/wd_non_back_el_china.jpeg',
    buyLink: 'https://weidian.com/item.html?itemID=6731491943',
    title: '【菲首】EL普版',
    brand: ['EL'],
    hit: ['可指定成员'],
    descLink: '',
    price: '¥ 78.5',
    shipping: 'non-back',
    onlyFelix: true,
    allVersion: false,
    ribbon: '',
    fansite: 'china',
  },
   {
    id: 'wd_non_back_kms_china',
    ver: ['rr'],
    image: './images/item/china/wd_non_back_kms_china.jpeg',
    buyLink: 'https://weidian.com/item.html?itemID=6729309842',
    title: '【菲首】KMS普版',
    brand: ['KMS'],
    hit: ['可指定成员'],
    descLink: '',
    price: '¥ 76.5',
    shipping: 'non-back',
    onlyFelix: true,
    allVersion: false,
    ribbon: '',
    fansite: 'china',
  },
  {
    id: 'wd_non_back_all_china',
    ver: ['rr', 'p', 'h'],
    image: './images/item/china/wd_non_back_all_china.jpeg',
    buyLink: 'https://weidian.com/item.html?itemID=6685289028',
    title: '【菲首】普版 / P版 / H版',
    brand: ['JYP', 'MK', 'YES24', 'MP', 'BDM', 'SW', '阿拉丁'],
    hit: [],
    descLink: '',
    price: '¥ 51.5~85.5',
    shipping: 'non-back',
    onlyFelix: false,
    allVersion: false,
    ribbon: '',
    fansite: 'china',
  },
  {
    id: 'wd_non_back_target_china',
    ver: ['rr'],
    image: './images/item/china/wd_non_back_target_china.jpeg',
    buyLink: 'https://weidian.com/item.html?itemID=6680825683',
    title: '【菲首】美网TARGET',
    brand: ['美网TARGET'],
    hit: [],
    descLink: '',
    price: '¥ 209',
    shipping: 'non-back',
    onlyFelix: false,
    allVersion: false,
    ribbon: '',
    fansite: 'china',
  },
  {
    id: 'wd_non_back_bn_china',
    ver: ['rr'],
    image: './images/item/china/wd_non_back_bn_china.jpeg',
    buyLink: 'https://weidian.com/item.html?itemID=6679476001',
    title: '【菲首】美网BN',
    brand: ['美网BN'],
    hit: ['BN特典书签'],
    descLink: '',
    price: '¥ 253',
    shipping: 'non-back',
    onlyFelix: false,
    allVersion: false,
    ribbon: '',
    fansite: 'china',
  },
  {
    id: 'wd_non_back_walmart_china',
    ver: ['rr'],
    image: './images/item/china/wd_non_back_walmart_china.jpeg',
    buyLink: 'https://weidian.com/item.html?itemID=6699244913',
    title: '【菲首】美网Walmart',
    brand: ['美网Walmart'],
    hit: ['Walmart特典明信片'],
    descLink: '',
    price: '¥ 219',
    shipping: 'non-back',
    onlyFelix: false,
    allVersion: false,
    ribbon: '',
    fansite: 'china',
  },
  {
    id: 'wd_non_back_fnac_china',
    ver: ['rr'],
    image: './images/item/china/wd_non_back_fnac_china.jpeg',
    buyLink: 'https://weidian.com/item.html?itemID=6690150900',
    title: '【菲首】法特Fnac',
    brand: ['法特Fnac'],
    hit: ['Fnac特典明信片'],
    descLink: '',
    price: '¥ 208',
    shipping: 'non-back',
    onlyFelix: false,
    allVersion: false,
    ribbon: '',
    fansite: 'china',
  },
]