const yetimallTitle = 'Yetimall';
const yetimallItems = [
  {
    id: 'yetimall_back_all_china',
    ver: ['rr', 'p', 'h'],
    image: './images/item/china/yetimall_back_all_china.jpeg',
    buyLink: 'https://www.yetimall.fun/h5/#/pages/store/goodsDetail/goodsDetail?gid=8857',
    title: '【菲首】一键毕业',
    brand: ['JYP', 'MK', 'YES24', 'MP', 'BDM', 'SW', '阿拉丁'],
    hit: ['2普+1P+1H'],
    descLink: 'https://weibo.com/6375947740/NmJ3WaRfS',
    price: '¥ 238~290',
    shipping: 'back',
    onlyFelix: false,
    allVersion: true,
    ribbon: '',
    fansite: 'china',
  },
  {
    id: 'yetimall_back_rr_china',
    ver: ['rr'],
    image: './images/item/china/yetimall_back_rr_china.jpeg',
    buyLink: 'https://www.yetimall.fun/h5/#/pages/store/goodsDetail/goodsDetail?gid=8761',
    title: '【菲首】普版',
    brand: ['JYP', 'MK', 'MP', 'BDM', 'SW', 'WM', 'MMT'],
    hit: [],
    descLink: '',
    price: '¥ 69~84',
    shipping: 'back',
    onlyFelix: false,
    allVersion: false,
    ribbon: '',
    fansite: 'china',
  },
  {
    id: 'yetimall_back_p_china',
    ver: ['p'],
    image: './images/item/china/yetimall_back_p_china.jpeg',
    buyLink: 'https://www.yetimall.fun/h5/#/pages/store/goodsDetail/goodsDetail?gid=8773',
    title: '【菲首】P版',
    brand: ['JYP', 'MK', 'YES24', 'MP', 'BDM', 'SW', '阿拉丁'],
    hit: [],
    descLink: '',
    price: '¥ 50~61',
    shipping: 'back',
    onlyFelix: false,
    allVersion: false,
    ribbon: '',
    fansite: 'china',
  },
  {
    id: 'yetimall_back_h_china',
    ver: ['h'],
    image: './images/item/china/yetimall_back_h_china.jpeg',
    buyLink: 'https://www.yetimall.fun/h5/#/pages/store/goodsDetail/goodsDetail?gid=8785',
    title: '【菲首】H版',
    brand: ['JYP', 'MK', 'YES24', 'MP', 'BDM', 'SW', '阿拉丁'],
    hit: [],
    descLink: '',
    price: '¥ 50~61',
    shipping: 'back',
    onlyFelix: false,
    allVersion: false,
    ribbon: '',
    fansite: 'china',
  },
  // gem
  {
    id: 'yetimall_back_all_gem',
    ver: ['rr', 'p', 'h'],
    image: './images/item/gem/yetimall_back_all_gem.jpeg',
    buyLink: 'https://www.yetimall.fun/h5/#/pages/store/goodsDetail/goodsDetail?gid=8856',
    title: '【宝石】一键毕业',
    brand: ['JYP', 'MK', 'YES24', 'MP', 'BDM', 'SW', '阿拉丁'],
    hit: ['2普+1P+1H'],
    descLink: 'https://weibo.com/5947554719/NmJ4MrKHr',
    price: '¥ 238~290',
    shipping: 'back',
    onlyFelix: false,
    allVersion: true,
    ribbon: '',
    fansite: 'gem',
  },
  {
    id: 'yetimall_back_rr_gem',
    ver: ['rr'],
    image: './images/item/gem/yetimall_back_rr_gem.jpeg',
    buyLink: 'https://www.yetimall.fun/h5/#/pages/store/goodsDetail/goodsDetail?gid=8760',
    title: '【宝石】普版',
    brand: ['JYP', 'MK', 'YES24', 'MP', 'BDM', 'SW', '阿拉丁'],
    hit: [],
    descLink: '',
    price: '¥ 69~84',
    shipping: 'back',
    onlyFelix: false,
    allVersion: false,
    ribbon: '',
    fansite: 'gem',
  },
  {
    id: 'yetimall_back_p_gem',
    ver: ['p'],
    image: './images/item/gem/yetimall_back_p_gem.jpeg',
    buyLink: 'https://www.yetimall.fun/h5/#/pages/store/goodsDetail/goodsDetail?gid=8772',
    title: '【宝石】P版',
    brand: ['JYP', 'MK', 'YES24', 'MP', 'BDM', 'SW', '阿拉丁'],
    hit: [],
    descLink: '',
    price: '¥ 50~61',
    shipping: 'back',
    onlyFelix: false,
    allVersion: false,
    ribbon: '',
    fansite: 'gem',
  },
  {
    id: 'yetimall_back_h_gem',
    ver: ['h'],
    image: './images/item/gem/yetimall_back_h_gem.jpeg',
    buyLink: 'https://www.yetimall.fun/h5/#/pages/store/goodsDetail/goodsDetail?gid=8784',
    title: '【宝石】H版',
    brand: ['JYP', 'MK', 'YES24', 'MP', 'BDM', 'SW', '阿拉丁'],
    hit: [],
    descLink: '',
    price: '¥ 50~61',
    shipping: 'back',
    onlyFelix: false,
    allVersion: false,
    ribbon: '',
    fansite: 'gem',
  },
  {
    id: 'yetimall_back_p_ald_mp_gem',
    ver: ['p'],
    image: './images/item/gem/yetimall_back_p_ald_mp_gem.jpeg',
    buyLink: 'https://weidian.com/item.html?itemID=6683914568',
    title: '【宝石】阿拉丁/MP P版1+1',
    brand: ['阿拉丁', 'MP'],
    hit: [],
    descLink: '',
    price: '¥ 111',
    shipping: 'back',
    onlyFelix: false,
    ribbon: '',
    fansite: 'gem',
  },
  {
    id: 'yetimall_back_p_ald_mp_1_gem',
    ver: ['p'],
    image: './images/item/gem/yetimall_back_p_ald_mp_1_gem.jpeg',
    buyLink: 'https://weidian.com/item.html?itemID=6682771501',
    title: '【宝石】MP P版2+2',
    brand: ['MP'],
    hit: [],
    descLink: '',
    price: '¥ 234',
    shipping: 'back',
    onlyFelix: true,
    ribbon: '',
    fansite: 'gem',
    soldOut: false,
  },
  {
    id: 'yetimall_back_p_ald_mp_2_gem',
    ver: ['p'],
    image: './images/item/gem/yetimall_back_p_ald_mp_2_gem.jpeg',
    buyLink: 'https://weidian.com/item.html?itemID=6682799525',
    title: '【宝石】阿拉丁/MP P版',
    brand: ['阿拉丁', 'MP'],
    hit: [],
    descLink: '',
    price: '¥ 55.5',
    shipping: 'back',
    onlyFelix: false,
    allVersion: false,
    ribbon: '',
    fansite: 'gem',
  },
]