const yetimallTitle = 'Yetimall';
const yetimallItems = [
  {
    id: 'yetimall_back_rr_china',
    ver: ['rr'],
    image: './images/item/yetimall_back_rr_china.jpeg',
    buyLink: 'https://www.yetimall.fun/h5/#/pages/store/goodsDetail/goodsDetail?gid=8761',
    title: '',
    brand: ['JYP', 'MK', 'YES24', 'MP', 'BDM', 'SW', 'ALD'],
    hit: [],
    descLink: '',
    price: '¥ 69~84',
    shipping: 'back',
    onlyFelix: false,
    ribbon: '',
  },
  {
    id: 'yetimall_back_p_china',
    ver: ['p'],
    image: './images/item/yetimall_back_p_china.jpeg',
    buyLink: 'https://www.yetimall.fun/h5/#/pages/store/goodsDetail/goodsDetail?gid=8773',
    title: '',
    brand: ['JYP', 'MK', 'YES24', 'MP', 'BDM', 'SW', 'ALD'],
    hit: [],
    descLink: '',
    price: '¥ 50~61',
    shipping: 'back',
    onlyFelix: false,
    ribbon: '',
  },
  {
    id: 'yetimall_back_h_china',
    ver: ['h'],
    image: './images/item/yetimall_back_h_china.jpeg',
    buyLink: 'https://www.yetimall.fun/h5/#/pages/store/goodsDetail/goodsDetail?gid=8785',
    title: '',
    brand: ['JYP', 'MK', 'YES24', 'MP', 'BDM', 'SW', 'ALD'],
    hit: [],
    descLink: '',
    price: '¥ 50~61',
    shipping: 'back',
    onlyFelix: false,
    ribbon: '',
  },
]