const yetimallTitle = 'Yetimall';
const yetimallItems = [
  {
    id: 'yetimall-back-abc-china',
    ver: ['abc'],
    image: './images/yetimall-abc.png',
    buyLink: 'https://www.yetimall.fun/h5/#/pages/store/goodsDetail/goodsDetail?gid=4812&continueFlag=89512eeeb5e9b2e411288376fc65ea57',
    title: '普版',
    brand: [],
    hit: [],
    descLink: '',
    price: '¥ 65',
    shipping: 'back',
    onlyFelix: false,
  },
  {
    id: 'yetimall-back-abc-8-china',
    ver: ['abc'],
    image: './images/yetimall-abc.png',
    buyLink: 'https://www.yetimall.fun/h5/#/pages/store/goodsDetail/goodsDetail?gid=4787&continueFlag=89512eeeb5e9b2e411288376fc65ea57',
    title: '普版',
    brand: ['SW', 'MP', 'JYP', 'BDM', 'MS', 'WM', 'MMT', 'EL'],
    hit: [],
    descLink: '',
    price: '¥ 74~90',
    shipping: 'back',
    onlyFelix: false,
  },
  {
    id: 'yetimall-back-abc-bdn-china',
    ver: ['abc'],
    image: './images/yeyimail-bandina.jpg',
    buyLink: 'https://www.yetimall.fun/h5/#/pages/store/goodsDetail/goodsDetail?gid=4943&continueFlag=407d506a7e76ce1b185a9a2faef09e43',
    title: '普版',
    brand: ['BDN'],
    hit: [],
    descLink: '',
    price: '¥ 84.5',
    shipping: 'back',
    onlyFelix: false,
  },
  {
    id: 'yetimall-back-abc-6-china',
    ver: ['abc'],
    image: './images/yetimall-wd-abc.jpg',
    buyLink: 'https://weidian.com/item.html?itemID=6268473597&wfr=c',
    title: '普版 (微店)',
    brand: ['SW', 'MP', 'BDM', 'WM'],
    hit: [],
    descLink: '',
    price: '¥ 65~90',
    shipping: 'back',
    onlyFelix: false,
  },
  {
    id: 'yetimall-back-d-china',
    ver: ['d'],
    image: './images/yetimall-d.jpg',
    buyLink: 'https://www.yetimall.fun/h5/#/pages/store/goodsDetail/goodsDetail?gid=4822&continueFlag=89512eeeb5e9b2e411288376fc65ea57',
    title: 'D版',
    brand: [],
    hit: [],
    descLink: '',
    price: '¥ 44',
    shipping: 'back',
    onlyFelix: false,
  },
  {
    id: 'yetimall-back-d-4-china',
    ver: ['d'],
    image: './images/yetimall-d.jpg',
    buyLink: 'https://www.yetimall.fun/h5/#/pages/store/goodsDetail/goodsDetail?gid=4795&continueFlag=89512eeeb5e9b2e411288376fc65ea57',
    title: 'D版',
    brand: ['SW', 'MP', 'JYP', 'BDM'],
    hit: [],
    descLink: '',
    price: '¥ 49~60',
    shipping: 'back',
    onlyFelix: false,
  },
  {
    id: 'yetimall-back-d-6-china',
    ver: ['d'],
    image: './images/yetimall-wd-d.jpg',
    buyLink: 'https://weidian.com/item.html?itemID=6268508125&wfr=c',
    title: 'D版 (微店)',
    brand: ['SW', 'MP', 'BDM'],
    hit: [],
    descLink: '',
    price: '¥ 44~60',
    shipping: 'back',
    onlyFelix: false,
  },
]