const yzyTitle = '一直娱';
const yzyItems = [
  {
    id: 'yzy_back_limit_china',
    ver: ['limit'],
    image: './images/item/china/yzy_back_limit_china.jpeg',
    buyLink: 'https://www.withfans.com/web/#/shopDetail/38BBB8653E90E6B8/0',
    title: '【菲首】限量版',
    brand: [],
    hit: [],
    descLink: '',
    price: '¥ 85',
    shipping: 'back',
    onlyFelix: false,
    ribbon: '',
    fansite: 'china',
  },
  {
    id: 'yzy_back_rr_china',
    ver: ['rr'],
    image: './images/item/china/yzy_back_rr_china.jpeg',
    buyLink: 'https://www.withfans.com/web/#/shopDetail/98AA752473395D2A/0',
    title: '【菲首】普版',
    brand: ['一直娱'],
    hit: [],
    descLink: '',
    price: '¥ 95',
    shipping: 'back',
    onlyFelix: false,
    ribbon: '',
    fansite: 'china',
  },
  {
    id: 'yzy_back_rr_1_china',
    ver: ['rr'],
    image: './images/item/china/yzy_back_rr_1_china.jpeg',
    buyLink: 'https://www.withfans.com/web/#/shopDetail/9D9D7D6A7DE37D87/0',
    title: '【菲首】一直娱普版1+1',
    brand: ['一直娱'],
    hit: [],
    descLink: '',
    price: '¥ 190',
    shipping: 'back',
    onlyFelix: true,
    ribbon: '',
    fansite: 'china',
    soldOut: true,
  },
  {
    id: 'yzy_back_rr_2_china',
    ver: ['rr'],
    image: './images/item/china/yzy_back_rr_2_china.jpeg',
    buyLink: 'https://weidian.com/item.html?itemID=6729023556',
    title: '【菲首】普版',
    brand: ['一直娱'],
    hit: [],
    descLink: '',
    price: '¥ 81.5',
    shipping: 'non-back',
    onlyFelix: false,
    ribbon: '',
    fansite: 'china',
  },
  // gem
  {
    id: 'yzy_back_limit_gem',
    ver: ['limit'],
    image: './images/item/gem/yzy_back_limit_gem.jpeg',
    buyLink: 'https://www.withfans.com/web/#/shopDetail/7A64C650A7B8CE79/0',
    title: '【宝石】限量版',
    brand: [],
    hit: [],
    descLink: '',
    price: '¥ 85',
    shipping: 'back',
    onlyFelix: false,
    ribbon: '',
    fansite: 'gem',
  },
  {
    id: 'yzy_back_rr_gem',
    ver: ['rr'],
    image: './images/item/gem/yzy_back_rr_gem.jpeg',
    buyLink: 'https://www.withfans.com/web/#/shopDetail/6F13BC642FDAE938/0',
    title: '【宝石】普版',
    brand: ['一直娱'],
    hit: [],
    descLink: '',
    price: '¥ 95',
    shipping: 'back',
    onlyFelix: false,
    ribbon: '',
    fansite: 'gem',
  },
  {
    id: 'yzy_back_rr_1_gem',
    ver: ['rr'],
    image: './images/item/gem/yzy_back_rr_1_gem.jpeg',
    buyLink: 'https://www.withfans.com/web/#/shopDetail/21C87A746B2ADB17/0',
    title: '【宝石】一直娱普版1+1',
    brand: ['一直娱'],
    hit: [],
    descLink: '',
    price: '¥ 190',
    shipping: 'back',
    onlyFelix: true,
    ribbon: '',
    fansite: 'gem',
    soldOut: false,
  },
  {
    id: 'yzy_back_rr_2_gem',
    ver: ['rr'],
    image: './images/item/gem/yzy_back_rr_2_gem.jpeg',
    buyLink: 'https://weidian.com/item.html?itemID=6729149930',
    title: '【宝石】普版',
    brand: ['一直娱'],
    hit: [],
    descLink: '',
    price: '¥ 81.5',
    shipping: 'non-back',
    onlyFelix: false,
    ribbon: '',
    fansite: 'gem',
  },
]