const yzyTitle = '一直娱';
const yzyItems = [
  {
    id: 'yzy_back_limit_china',
    ver: ['limit'],
    image: './images/item/china/yzy_back_limit_china.jpeg',
    buyLink: 'https://www.withfans.com/web/#/shopDetail/38BBB8653E90E6B8/0',
    title: '【菲首】限量版',
    brand: [],
    hit: [],
    descLink: '',
    price: '¥ 85',
    shipping: 'back',
    onlyFelix: false,
    allVersion: false,
    ribbon: '',
    fansite: 'china',
  },
  {
    id: 'yzy_back_limit_gem',
    ver: ['limit'],
    image: './images/item/gem/yzy_back_limit_gem.jpeg',
    buyLink: 'https://www.withfans.com/web/#/shopDetail/7A64C650A7B8CE79/0',
    title: '【宝石】限量版',
    brand: [],
    hit: [],
    descLink: '',
    price: '¥ 85',
    shipping: 'back',
    onlyFelix: false,
    allVersion: false,
    ribbon: '',
    fansite: 'gem',
  },
]